# Generated by Django 3.2.25 on 2025-12-04 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0013_clinicalhistory_allergic_history_and_more'),
        ('organizations', '0008_auto_20251203_1942'),
        ('appointments', '0006_alter_appointment_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_users', models.IntegerField(default=0, verbose_name='Usuarios Activos')),
                ('appointments_today', models.IntegerField(default=0, verbose_name='Citas Hoy')),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos Hoy')),
                ('pending_appointments', models.IntegerField(default=0, verbose_name='Citas Pendientes')),
                ('appointments_trend', models.CharField(default='stable', max_length=10, verbose_name='Tendencia Citas')),
                ('revenue_trend', models.CharField(default='stable', max_length=10, verbose_name='Tendencia Ingresos')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_metrics', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Métrica en Tiempo Real',
                'verbose_name_plural': 'Métricas en Tiempo Real',
            },
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del KPI')),
                ('metric_type', models.CharField(max_length=50, verbose_name='Tipo de Métrica')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Actual')),
                ('period_start', models.DateField(verbose_name='Inicio del Período')),
                ('period_end', models.DateField(verbose_name='Fin del Período')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('achieved', models.BooleanField(default=False, verbose_name='Alcanzado')),
                ('achievement_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Logro')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpitarget_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Objetivo KPI',
                'verbose_name_plural': 'Objetivos KPI',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hour', models.IntegerField(verbose_name='Hora (0-23)')),
                ('appointment_count', models.IntegerField(default=0, verbose_name='Total de Citas')),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos Totales')),
                ('period_start', models.DateField(verbose_name='Inicio del Período')),
                ('period_end', models.DateField(verbose_name='Fin del Período')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heatmapdata_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Dato de Heatmap',
                'verbose_name_plural': 'Datos de Heatmap',
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('metric_type', models.CharField(choices=[('revenue', 'Ingresos'), ('appointments', 'Citas'), ('patients', 'Pacientes'), ('sales', 'Ventas'), ('conversion', 'Conversión')], max_length=50, verbose_name='Tipo de Métrica')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('count', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Anterior')),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Cambio')),
                ('details', models.TextField(blank=True, default='{}', verbose_name='Detalles JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboardmetric_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Métrica del Dashboard',
                'verbose_name_plural': 'Métricas del Dashboard',
                'ordering': ['-date', 'metric_type'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(default=5, verbose_name='Calificación General')),
                ('service_rating', models.IntegerField(default=5, verbose_name='Calificación de Servicio')),
                ('quality_rating', models.IntegerField(default=5, verbose_name='Calificación de Calidad')),
                ('speed_rating', models.IntegerField(default=5, verbose_name='Calificación de Rapidez')),
                ('nps_score', models.IntegerField(blank=True, help_text='¿Qué tan probable es que nos recomiende?', null=True, verbose_name='Puntuación NPS (0-10)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('survey_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Encuesta')),
                ('responded_via', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('in_person', 'En Persona'), ('web', 'Página Web')], default='web', max_length=50, verbose_name='Respondió Vía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_survey', to='appointments.appointment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customersatisfaction_set', to='organizations.organization', verbose_name='Organización')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
                'verbose_name_plural': 'Encuestas de Satisfacción',
                'ordering': ['-survey_date'],
            },
        ),
        migrations.AddIndex(
            model_name='heatmapdata',
            index=models.Index(fields=['organization', 'period_start', 'period_end'], name='dashboard_h_organiz_3dcc90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heatmapdata',
            unique_together={('organization', 'day_of_week', 'hour', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['organization', 'date', 'metric_type'], name='dashboard_d_organiz_f8ba7f_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['organization', 'metric_type', '-date'], name='dashboard_d_organiz_d2951a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetric',
            unique_together={('organization', 'date', 'metric_type')},
        ),
    ]
