# Generated by Django 3.2.25 on 2025-12-04 23:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_clinicalhistory_allergic_history_and_more'),
        ('organizations', '0008_auto_20251203_1942'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceShapeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_shape', models.CharField(choices=[('oval', 'Óvalo'), ('round', 'Redondo'), ('square', 'Cuadrado'), ('heart', 'Corazón'), ('triangle', 'Triángulo'), ('diamond', 'Diamante')], max_length=50, unique=True)),
                ('recommended_styles', models.TextField(verbose_name='Estilos Recomendados')),
                ('avoid_styles', models.TextField(verbose_name='Estilos a Evitar')),
                ('tips', models.TextField(verbose_name='Consejos')),
                ('ideal_frame_width', models.CharField(blank=True, max_length=100, verbose_name='Ancho Ideal')),
                ('ideal_frame_shapes', models.CharField(blank=True, max_length=200, verbose_name='Formas Ideales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recomendación por Forma de Rostro',
                'verbose_name_plural': 'Recomendaciones por Forma de Rostro',
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('material', models.CharField(choices=[('metal', 'Metal'), ('acetate', 'Acetato'), ('titanium', 'Titanio'), ('plastic', 'Plástico'), ('mixed', 'Mixto')], max_length=50, verbose_name='Material')),
                ('gender', models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Hombre'), ('female', 'Mujer'), ('kids', 'Niños')], default='unisex', max_length=20, verbose_name='Género')),
                ('lens_width', models.IntegerField(help_text='En milímetros', verbose_name='Ancho de lente')),
                ('bridge_width', models.IntegerField(help_text='En milímetros', verbose_name='Ancho de puente')),
                ('temple_length', models.IntegerField(help_text='En milímetros', verbose_name='Largo de patilla')),
                ('recommended_face_shapes', models.CharField(blank=True, help_text='Separadas por comas: oval,round,square', max_length=200, verbose_name='Formas de rostro recomendadas')),
                ('front_image', models.ImageField(upload_to='ar_frames/front/', verbose_name='Imagen Frontal')),
                ('side_image', models.ImageField(blank=True, upload_to='ar_frames/side/', verbose_name='Imagen Lateral')),
                ('overlay_image', models.ImageField(blank=True, help_text='PNG transparente con la montura para superponer en rostro', upload_to='ar_frames/overlay/', verbose_name='Imagen para Overlay AR')),
                ('anchor_points', models.TextField(blank=True, help_text='Coordenadas de referencia para posicionar la montura: {left_eye: {x, y}, right_eye: {x, y}, bridge: {x, y}}', verbose_name='Puntos de Anclaje JSON')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('try_on_count', models.IntegerField(default=0, verbose_name='Veces Probado')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='Favoritos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Montura',
                'verbose_name_plural': 'Monturas',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameTryOnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='ar_tryon_photos/%Y/%m/%d/', verbose_name='Foto Capturada')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Calificación (1-5)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('view_duration', models.IntegerField(default=0, verbose_name='Tiempo de Visualización (segundos)')),
                ('tried_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='try_records', to='dashboard.frame')),
            ],
            options={
                'verbose_name': 'Registro de Prueba',
                'verbose_name_plural': 'Registros de Pruebas',
                'ordering': ['-tried_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTryOnSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_shape_detected', models.CharField(blank=True, max_length=50, verbose_name='Forma de Rostro Detectada')),
                ('face_measurements', models.TextField(blank=True, help_text='Distancia entre ojos, ancho de cara, etc.', verbose_name='Medidas Faciales JSON')),
                ('session_duration', models.IntegerField(default=0, verbose_name='Duración (segundos)')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Info del Dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frames_tried', models.ManyToManyField(related_name='sessions', through='dashboard.FrameTryOnRecord', to='dashboard.Frame', verbose_name='Monturas Probadas')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualtryonsession_set', to='organizations.organization', verbose_name='Organización')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tryon_sessions', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Sesión de Prueba Virtual',
                'verbose_name_plural': 'Sesiones de Prueba Virtual',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='frametryonrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='try_records', to='dashboard.virtualtryonsession'),
        ),
        migrations.CreateModel(
            name='FrameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono Font Awesome')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framecategory_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Categoría de Montura',
                'verbose_name_plural': 'Categorías de Monturas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frames', to='dashboard.framecategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='frame',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['organization', 'is_active', '-is_featured'], name='dashboard_f_organiz_b9087d_idx'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['organization', 'category', 'is_active'], name='dashboard_f_organiz_6e0c2c_idx'),
        ),
    ]
