# Generated by Django 3.2.25 on 2025-12-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_modulepermission_organizationmember_invited_by_and_more'),
        ('dashboard', '0003_alter_customersatisfaction_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2, verbose_name='Tipo de Documento')),
                ('identification', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('position', models.CharField(choices=[('RECEPCIONISTA', 'Recepcionista'), ('VENDEDOR', 'Vendedor'), ('TECNICO_OPTICO', 'Técnico Óptico'), ('ASISTENTE', 'Asistente'), ('GERENTE', 'Gerente'), ('ADMINISTRATIVO', 'Administrativo'), ('CONTADOR', 'Contador'), ('OTRO', 'Otro')], max_length=50, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'identification'), name='unique_employee_per_organization'),
        ),
    ]
