# Generated by Django 3.2.25 on 2026-01-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0023_alter_organizationmember_role'),
        ('dashboard', '0005_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('patient_create', 'Creó un paciente'), ('patient_edit', 'Editó un paciente'), ('patient_delete', 'Eliminó un paciente'), ('invoice_create', 'Creó una factura'), ('invoice_edit', 'Editó una factura'), ('invoice_delete', 'Eliminó una factura'), ('invoice_void', 'Anuló una factura'), ('product_create', 'Creó un producto'), ('product_edit', 'Editó un producto'), ('product_delete', 'Eliminó un producto'), ('supplier_create', 'Creó un proveedor'), ('supplier_edit', 'Editó un proveedor'), ('supplier_delete', 'Eliminó un proveedor'), ('sale_create', 'Registró una venta'), ('sale_edit', 'Editó una venta'), ('sale_delete', 'Eliminó una venta'), ('appointment_create', 'Creó una cita'), ('appointment_edit', 'Modificó una cita'), ('appointment_cancel', 'Canceló una cita'), ('appointment_complete', 'Completó una cita'), ('doctor_create', 'Registró un doctor'), ('doctor_edit', 'Editó un doctor'), ('doctor_delete', 'Eliminó un doctor'), ('clinical_create', 'Creó historia clínica'), ('clinical_edit', 'Editó historia clínica'), ('exam_create', 'Registró un examen'), ('exam_edit', 'Editó un examen'), ('exam_delete', 'Eliminó un examen'), ('login', 'Inició sesión'), ('logout', 'Cerró sesión'), ('member_add', 'Agregó un miembro'), ('member_edit', 'Editó un miembro'), ('member_remove', 'Eliminó un miembro'), ('permissions_change', 'Cambió permisos')], max_length=50)),
                ('description', models.TextField()),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='dashboard_a_created_818b51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='dashboard_a_organiz_9b85fb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_df6777_idx'),
        ),
    ]
