# Generated by Django 3.2.25 on 2026-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20260102_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
