# Generated by Django 3.2.25 on 2026-01-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_auditlog_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ciudad',
            field=models.CharField(blank=True, default='Bogotá', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departamento_ubicacion',
            field=models.CharField(blank=True, default='Cundinamarca', max_length=100, verbose_name='Departamento/Estado'),
        ),
        migrations.AddField(
            model_name='employee',
            name='incluir_en_nomina',
            field=models.BooleanField(default=False, help_text='Si está activado, este empleado aparecerá en el módulo de nómina electrónica', verbose_name='Incluir en Nómina'),
        ),
    ]
