# Generated by Django 5.2.8 on 2026-01-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20260106_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
