# Generated by Django 3.2.25 on 2026-01-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_auditlog_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
