# Generated by Django 3.2.25 on 2026-01-09 00:10

import apps.tasks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('on_hold', 'En Espera'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=20, verbose_name='Prioridad')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Objeto')),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha Límite')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada en')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado en horas', max_digits=6, null=True, verbose_name='Horas Estimadas')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo real invertido en horas', max_digits=6, null=True, verbose_name='Horas Reales')),
                ('progress', models.IntegerField(default=0, help_text='Porcentaje de completitud (0-100)', verbose_name='Progreso')),
                ('tags', apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Lista de etiquetas para clasificación', verbose_name='Etiquetas')),
                ('attachments', apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Referencias a documentos adjuntos', verbose_name='Adjuntos')),
                ('metadata', apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Datos adicionales personalizados', verbose_name='Metadata')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es Recurrente')),
                ('recurrence_rule', models.CharField(blank=True, help_text='Regla RRULE para tareas recurrentes', max_length=255, verbose_name='Regla de Recurrencia')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('push', 'Notificación Push'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Tipo')),
                ('remind_at', models.DateTimeField(db_index=True, help_text='Fecha y hora del recordatorio', verbose_name='Recordar en')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('is_sent', models.BooleanField(db_index=True, default=False, verbose_name='Enviado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to='organizations.organization', verbose_name='Organización')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task', verbose_name='Tarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recordatorio de Tarea',
                'verbose_name_plural': 'Recordatorios de Tareas',
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('attachments', apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, verbose_name='Adjuntos')),
                ('is_internal', models.BooleanField(default=False, help_text='Comentario solo visible para el equipo', verbose_name='Es Interno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='organizations.organization', verbose_name='Organización')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment', verbose_name='Comentario Padre')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Tarea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de Tarea',
                'verbose_name_plural': 'Comentarios de Tareas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('items', apps.tasks.models.JSONFieldCompatible(default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Lista de items del checklist con estado', verbose_name='Items')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_checklists', to='organizations.organization', verbose_name='Organización')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='tasks.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Checklist de Tarea',
                'verbose_name_plural': 'Checklists de Tareas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#3498db', help_text='Color en formato hexadecimal (#RRGGBB)', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: fas fa-tasks)', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_categories', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Categoría de Tarea',
                'verbose_name_plural': 'Categorías de Tareas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('assigned', 'Asignada'), ('status_changed', 'Estado Cambiado'), ('priority_changed', 'Prioridad Cambiada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('commented', 'Comentada'), ('attachment_added', 'Adjunto Agregado'), ('due_date_changed', 'Fecha Límite Cambiada')], db_index=True, max_length=50, verbose_name='Acción')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('old_value', apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, verbose_name='Valor Anterior')),
                ('new_value', apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, verbose_name='Valor Nuevo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='organizations.organization', verbose_name='Organización')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task', verbose_name='Tarea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de Tarea',
                'verbose_name_plural': 'Actividades de Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Tarea Padre'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['remind_at', 'is_sent'], name='tasks_taskr_remind__0547fe_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['task', 'user'], name='tasks_taskr_task_id_5bb836_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['organization', 'remind_at'], name='tasks_taskr_organiz_6c7b71_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taskc_task_id_3f97e8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['organization', 'created_at'], name='tasks_taskc_organiz_cf6a03_idx'),
        ),
        migrations.AddIndex(
            model_name='taskchecklist',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taskc_task_id_410c36_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcategory',
            index=models.Index(fields=['organization', 'is_active'], name='tasks_taskc_organiz_b4a88f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcategory',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taska_task_id_88cdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['organization', 'action'], name='tasks_taska_organiz_6f724e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['user', 'created_at'], name='tasks_taska_user_id_c8933e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'status'], name='tasks_task_organiz_ab0744_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_task_assigne_b3b2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='tasks_task_due_dat_3f7773_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'status'], name='tasks_task_priorit_685c61_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category', 'status'], name='tasks_task_categor_55ce6c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['content_type', 'object_id'], name='tasks_task_content_2bbe5a_idx'),
        ),
    ]
