# Generated by Django 3.2.25 on 2026-01-09 18:53

import apps.tasks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20260108_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Referencias a documentos adjuntos', verbose_name='Adjuntos'),
        ),
        migrations.AlterField(
            model_name='task',
            name='metadata',
            field=apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Datos adicionales personalizados', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Lista de etiquetas para clasificación', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='new_value',
            field=apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, verbose_name='Valor Nuevo'),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='old_value',
            field=apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, verbose_name='Valor Anterior'),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='items',
            field=apps.tasks.models.JSONFieldCompatible(default=apps.tasks.models.JSONFieldCompatible._get_default, help_text='Lista de items del checklist con estado', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='attachments',
            field=apps.tasks.models.JSONFieldCompatible(blank=True, default=apps.tasks.models.JSONFieldCompatible._get_default, verbose_name='Adjuntos'),
        ),
    ]
