# Generated by Django 3.2.25 on 2026-01-09 00:01

import apps.api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la API Key', max_length=255, verbose_name='Nombre')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Key')),
                ('key_prefix', models.CharField(db_index=True, max_length=8, verbose_name='Prefijo')),
                ('key_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash')),
                ('scope', models.CharField(choices=[('read', 'Solo Lectura'), ('write', 'Lectura y Escritura'), ('admin', 'Administrador')], default='read', help_text='Nivel de permisos de la API Key', max_length=20, verbose_name='Alcance')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('revoked', 'Revocada'), ('expired', 'Expirada')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('allowed_ips', apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de IPs permitidas (vacío = todas)', verbose_name='IPs Permitidas')),
                ('allowed_endpoints', apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de endpoints permitidos (vacío = todos)', verbose_name='Endpoints Permitidos')),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests por hora permitidos', verbose_name='Límite de Tasa')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración (null = sin expiración)', null=True, verbose_name='Expira en')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total Requests')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(help_text='Usuario propietario de esta API Key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('api_key', 'API Key'), ('ip_address', 'IP Address'), ('user', 'Usuario')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('identifier', models.CharField(db_index=True, max_length=255, verbose_name='Identificador')),
                ('endpoint', models.CharField(db_index=True, max_length=500, verbose_name='Endpoint')),
                ('request_count', models.IntegerField(default=0, verbose_name='Contador Requests')),
                ('window_start', models.DateTimeField(db_index=True, verbose_name='Inicio Ventana')),
                ('window_end', models.DateTimeField(db_index=True, verbose_name='Fin Ventana')),
                ('limit', models.IntegerField(help_text='Número máximo de requests en la ventana', verbose_name='Límite')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, verbose_name='Bloqueado')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='api.apikey', verbose_name='API Key')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='organizations.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Rate Limit',
                'verbose_name_plural': 'Registros Rate Limit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('url', models.URLField(help_text='URL donde se enviarán los webhooks', max_length=500, verbose_name='URL')),
                ('events', apps.api.models.JSONFieldCompatible(default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de eventos a los que está suscrito', verbose_name='Eventos')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('failed', 'Fallido')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('headers', apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Headers HTTP personalizados a incluir', verbose_name='Headers Personalizados')),
                ('secret', models.CharField(blank=True, help_text='Secret para firmar payloads (HMAC)', max_length=64, verbose_name='Secret')),
                ('retry_on_failure', models.BooleanField(default=True, verbose_name='Reintentar en Fallo')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Máximo Reintentos')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Trigger')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Éxito')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Fallo')),
                ('total_triggers', models.IntegerField(default=0, verbose_name='Total Triggers')),
                ('total_successes', models.IntegerField(default=0, verbose_name='Total Éxitos')),
                ('total_failures', models.IntegerField(default=0, verbose_name='Total Fallos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('api_key', models.ForeignKey(help_text='API Key asociada a este webhook', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api.apikey', verbose_name='API Key')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Webhook API',
                'verbose_name_plural': 'Webhooks API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], db_index=True, max_length=10, verbose_name='Método HTTP')),
                ('endpoint', models.CharField(db_index=True, max_length=500, verbose_name='Endpoint')),
                ('full_path', models.TextField(verbose_name='Path Completo')),
                ('request_headers', apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Headers Request')),
                ('request_body', apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Body Request')),
                ('request_params', apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Query Params')),
                ('response_status', models.IntegerField(db_index=True, verbose_name='Status Code')),
                ('response_body', apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Body Response')),
                ('response_time', models.FloatField(help_text='Tiempo en milisegundos', verbose_name='Tiempo Respuesta (ms)')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje Error')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack Trace')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.apikey', verbose_name='API Key')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='organizations.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log API',
                'verbose_name_plural': 'Logs API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ratelimitrecord',
            index=models.Index(fields=['organization', 'window_end'], name='api_ratelim_organiz_5c79b5_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitrecord',
            index=models.Index(fields=['identifier', 'endpoint', 'window_end'], name='api_ratelim_identif_8f889b_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitrecord',
            index=models.Index(fields=['is_blocked', 'blocked_until'], name='api_ratelim_is_bloc_5d17a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitrecord',
            unique_together={('limit_type', 'identifier', 'endpoint', 'window_start')},
        ),
        migrations.AddIndex(
            model_name='apiwebhook',
            index=models.Index(fields=['organization', 'status'], name='api_apiwebh_organiz_38ff7d_idx'),
        ),
        migrations.AddIndex(
            model_name='apiwebhook',
            index=models.Index(fields=['api_key', 'is_active'], name='api_apiwebh_api_key_47aa88_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['organization', 'created_at'], name='api_apilog_organiz_409807_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['api_key', 'created_at'], name='api_apilog_api_key_f4074b_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['user', 'created_at'], name='api_apilog_user_id_388989_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['endpoint', 'method'], name='api_apilog_endpoin_dd64da_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['response_status', 'created_at'], name='api_apilog_respons_685bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['ip_address', 'created_at'], name='api_apilog_ip_addr_bca26b_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'status'], name='api_apikey_organiz_104e42_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'status'], name='api_apikey_user_id_52285c_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix', 'key_hash'], name='api_apikey_key_pre_867332_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['expires_at'], name='api_apikey_expires_f6e5a1_idx'),
        ),
    ]
