# Generated by Django 3.2.25 on 2026-01-09 18:53

import apps.api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260108_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='allowed_endpoints',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de endpoints permitidos (vacío = todos)', verbose_name='Endpoints Permitidos'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='allowed_ips',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de IPs permitidas (vacío = todas)', verbose_name='IPs Permitidas'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_body',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Body Request'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_headers',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Headers Request'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_params',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Query Params'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_body',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Body Response'),
        ),
        migrations.AlterField(
            model_name='apiwebhook',
            name='events',
            field=apps.api.models.JSONFieldCompatible(default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de eventos a los que está suscrito', verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='apiwebhook',
            name='headers',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Headers HTTP personalizados a incluir', verbose_name='Headers Personalizados'),
        ),
    ]
