# Generated by Django 4.2.16 on 2026-01-13 20:57

import apps.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        ('api', '0004_alter_apikey_allowed_endpoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='allowed_endpoints',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de endpoints permitidos (vacío = todos)', verbose_name='Endpoints Permitidos'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='allowed_ips',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de IPs permitidas (vacío = todas)', verbose_name='IPs Permitidas'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_body',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Body Request'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_headers',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Headers Request'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_params',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Query Params'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_body',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, verbose_name='Body Response'),
        ),
        migrations.AlterField(
            model_name='apiwebhook',
            name='events',
            field=apps.api.models.JSONFieldCompatible(default=apps.api.models.JSONFieldCompatible._get_default, help_text='Lista de eventos a los que está suscrito', verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='apiwebhook',
            name='headers',
            field=apps.api.models.JSONFieldCompatible(blank=True, default=apps.api.models.JSONFieldCompatible._get_default, help_text='Headers HTTP personalizados a incluir', verbose_name='Headers Personalizados'),
        ),
        migrations.AlterField(
            model_name='ratelimitrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='organizations.organization', verbose_name='Organización'),
        ),
    ]
