# Generated by Django 3.2.25 on 2025-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20251216_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianconfiguration',
            name='ciudad_codigo',
            field=models.CharField(blank=True, help_text='Ej: 11001 para Bogotá', max_length=10, verbose_name='Código Ciudad DIVIPOLA'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='ciudad_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Ciudad'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='departamento_codigo',
            field=models.CharField(blank=True, help_text='Ej: 11 para Cundinamarca', max_length=10, verbose_name='Código Departamento'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='departamento_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Departamento'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='dv',
            field=models.CharField(blank=True, help_text='Dígito de verificación del NIT', max_length=1, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='email_facturacion',
            field=models.EmailField(blank=True, help_text='Email desde el cual se enviarán facturas', max_length=254, verbose_name='Email Facturación'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='nit',
            field=models.CharField(blank=True, help_text='NIT sin dígito de verificación. Ej: 900123456', max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal de la empresa', max_length=300, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='resolucion_clave_tecnica',
            field=models.CharField(blank=True, help_text='Clave técnica proporcionada por la DIAN', max_length=500, verbose_name='Clave Técnica'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='resolucion_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='resolucion_numero',
            field=models.CharField(blank=True, help_text='Número asignado por la DIAN', max_length=50, verbose_name='Número de Resolución'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='resolucion_numero_fin',
            field=models.PositiveIntegerField(blank=True, help_text='Último número del rango autorizado', null=True, verbose_name='Número Final'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='resolucion_numero_inicio',
            field=models.PositiveIntegerField(blank=True, help_text='Primer número del rango autorizado', null=True, verbose_name='Número Inicial'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='resolucion_vigencia_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia Hasta'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='resolucion_vigencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia Desde'),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
    ]
