# Generated by Django 3.2.25 on 2025-12-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_subscriptionplan_max_organizations'),
        ('billing', '0003_auto_20251216_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('RUT', 'RUT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='NIT', max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la categoría (ej: MONTURAS, LENTES)', max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la categoría', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliercategory_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Categoría de Proveedor',
                'verbose_name_plural': 'Categorías de Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='suppliercategory',
            index=models.Index(fields=['organization', 'activo'], name='billing_sup_organiz_42308e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('organization', 'codigo')},
        ),
    ]
