# Generated by Django 3.2.25 on 2025-12-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20251216_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='dianconfiguration',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT - Número de Identificación Tributaria'), ('RUT', 'RUT - Registro Único Tributario'), ('CC', 'CC - Cédula de Ciudadanía'), ('CE', 'CE - Cédula de Extranjería'), ('PA', 'PA - Pasaporte')], default='NIT', max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
