# Generated by Django 3.2.25 on 2025-12-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_dianconfiguration_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='permitir_pagos_parciales',
            field=models.BooleanField(default=True, help_text='Permitir abonos y pagos parciales en facturas', verbose_name='Permitir Pagos Parciales'),
        ),
    ]
