# Generated by Django 3.2.25 on 2025-12-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoiceconfiguration_permitir_pagos_parciales'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceconfiguration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='invoiceconfiguration',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_invoiceconfig_per_org'),
        ),
    ]
