# Generated by Django 3.2.25 on 2025-12-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoiceconfig_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='ambiente',
            field=models.CharField(choices=[('pruebas', 'Habilitación / Pruebas'), ('produccion', 'Producción')], default='pruebas', help_text='Ambiente para facturación electrónica', max_length=20, verbose_name='Ambiente DIAN'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='certificado_digital',
            field=models.FileField(blank=True, help_text='Archivo .p12 o .pfx del certificado digital', null=True, upload_to='billing/certificates/', verbose_name='Certificado Digital'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='certificado_password',
            field=models.CharField(blank=True, help_text='Contraseña del certificado digital', max_length=200, verbose_name='Contraseña del Certificado'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='facturacion_electronica_activa',
            field=models.BooleanField(default=False, help_text='Activar procesamiento de facturación electrónica DIAN', verbose_name='Facturación Electrónica Activa'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='prefijo',
            field=models.CharField(default='FE', help_text='Prefijo para numeración (ej: FE, FEPV)', max_length=10, verbose_name='Prefijo'),
        ),
    ]
