# Generated by Django 3.2.25 on 2025-12-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20251216_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dianconfiguration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dianconfiguration',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_dianconfig_per_org'),
        ),
    ]
