# Generated by Django 3.2.25 on 2025-12-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_update_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='email_asunto',
            field=models.CharField(default='Factura Electrónica #{numero_factura}', help_text='Asunto del correo electrónico. Use {numero_factura}, {cliente}, {total} como variables', max_length=200, verbose_name='Asunto del Email'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='email_mensaje',
            field=models.TextField(default='Estimado(a) cliente,\n\nAdjuntamos su factura electrónica.\n\nGracias por su compra.', help_text='Mensaje del cuerpo del correo electrónico', verbose_name='Mensaje del Email'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='email_remitente',
            field=models.EmailField(blank=True, help_text='Email desde el cual se enviarán las facturas (dejar vacío para usar email de la organización)', max_length=254, verbose_name='Email Remitente'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='enviar_email_factura',
            field=models.BooleanField(default=True, help_text='Enviar factura automáticamente por email al cliente', verbose_name='Enviar Factura por Email'),
        ),
    ]
