# Generated by Django 3.2.25 on 2025-12-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_email_configuration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='Ej: smtp.gmail.com, smtp.office365.com', max_length=255, verbose_name='Servidor SMTP'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Contraseña o contraseña de aplicación para SMTP', max_length=255, verbose_name='Contraseña SMTP'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='Puerto del servidor SMTP (587 para TLS, 465 para SSL)', verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Activar TLS para conexión segura', verbose_name='Usar TLS'),
        ),
        migrations.AddField(
            model_name='invoiceconfiguration',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='Email completo para autenticación SMTP', max_length=254, verbose_name='Usuario SMTP'),
        ),
        migrations.AlterField(
            model_name='invoiceconfiguration',
            name='email_remitente',
            field=models.EmailField(blank=True, help_text='Email desde el cual se enviarán las facturas', max_length=254, verbose_name='Email Remitente'),
        ),
    ]
