# Generated by Django 3.2.25 on 2025-12-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_add_smtp_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='numero_completo',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Número Completo'),
        ),
    ]
