# Generated by Django 5.2.8 on 2025-12-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_unique_constraint_numero_completo'),
        ('organizations', '0012_subscriptionplan_max_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianconfiguration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='invoiceconfiguration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
    ]
