# Generated by Django 3.2.25 on 2026-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_add_factura_electronica_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianconfiguration',
            name='responsabilidades_fiscales',
            field=models.TextField(default='[]', help_text="Ej: ['O-13', 'O-15', 'R-99-PN'] - JSON string", verbose_name='Responsabilidades Fiscales'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dian_response',
            field=models.TextField(blank=True, default='{}', help_text='JSON completo de la respuesta de la DIAN', null=True, verbose_name='Respuesta DIAN'),
        ),
        migrations.AlterField(
            model_name='invoiceconfiguration',
            name='metodos_pago_disponibles',
            field=models.TextField(default='[]', help_text='Lista de métodos de pago aceptados - JSON string', verbose_name='Métodos de Pago Disponibles'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='especificaciones',
            field=models.TextField(blank=True, default='{}', help_text='Datos adicionales en formato JSON', verbose_name='Especificaciones Técnicas'),
        ),
    ]
