# Generated by Django 5.2.8 on 2026-01-08 14:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        ('sales', '0004_cascade_delete_on_user_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Caja')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='CLOSED', max_length=10, verbose_name='Estado')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo Actual')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Apertura')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto de Apertura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='organizations.organization', verbose_name='Organización')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Actual')),
            ],
            options={
                'verbose_name': 'Caja Registradora',
                'verbose_name_plural': 'Cajas Registradoras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso'), ('OPENING', 'Apertura'), ('CLOSURE', 'Cierre')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('category', models.CharField(choices=[('SALE', 'Venta'), ('PAYMENT_RECEIVED', 'Cobro a Cliente'), ('REFUND', 'Devolución de Proveedor'), ('OTHER_INCOME', 'Otro Ingreso'), ('PURCHASE', 'Compra'), ('PAYMENT_MADE', 'Pago a Proveedor'), ('SALARY', 'Pago de Nómina'), ('EXPENSE', 'Gasto Operativo'), ('REFUND_CUSTOMER', 'Devolución a Cliente'), ('WITHDRAWAL', 'Retiro de Efectivo'), ('OTHER_EXPENSE', 'Otro Egreso'), ('OPENING', 'Apertura de Caja'), ('CLOSURE', 'Cierre de Caja')], max_length=20, verbose_name='Categoría')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('OTHER', 'Otro')], default='CASH', max_length=10, verbose_name='Método de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia (Nº Factura, Recibo, etc.)')),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Anterior')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Posterior')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='organizations.organization', verbose_name='Organización')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.sale', verbose_name='Venta Relacionada')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cash_register.cashregister', verbose_name='Caja Registradora')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure_date', models.DateField(verbose_name='Fecha de Cierre')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto de Apertura')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ingresos')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Egresos')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Esperado (Sistema)')),
                ('counted_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Efectivo Contado')),
                ('counted_cards', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Tarjetas')),
                ('counted_transfers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Transferencias')),
                ('counted_checks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Cheques')),
                ('counted_other', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Otros Métodos')),
                ('total_counted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Contado')),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Diferencia (Contado - Esperado)')),
                ('denomination_breakdown', models.JSONField(blank=True, default=dict, verbose_name='Desglose de Denominaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas/Observaciones')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWED', 'Revisado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Creación')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Revisión')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_created', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado Por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_closures', to='organizations.organization', verbose_name='Organización')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='cash_register.cashregister', verbose_name='Caja Registradora')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-closure_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['organization', 'status'], name='cash_regist_organiz_4619a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['responsible'], name='cash_regist_respons_879bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['-created_at'], name='cash_regist_created_35c25b_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['cash_register', '-created_at'], name='cash_regist_cash_re_4b6fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['organization', 'movement_type'], name='cash_regist_organiz_ede2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['category'], name='cash_regist_categor_307994_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['created_at'], name='cash_regist_created_09c82e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashclosure',
            index=models.Index(fields=['cash_register', '-closure_date'], name='cash_regist_cash_re_f4407f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashclosure',
            index=models.Index(fields=['organization', 'status'], name='cash_regist_organiz_fd2ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashclosure',
            index=models.Index(fields=['-created_at'], name='cash_regist_created_7b7d4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashclosure',
            unique_together={('cash_register', 'closure_date')},
        ),
    ]
