# Generated by Django 5.2.8 on 2026-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='category',
            field=models.CharField(choices=[('SALE', 'Venta de Producto'), ('SALE_GLASSES', 'Venta de Lentes'), ('SALE_FRAMES', 'Venta de Monturas'), ('SALE_CONTACTS', 'Venta de Lentes de Contacto'), ('SALE_ACCESSORIES', 'Venta de Accesorios'), ('EXAM_PAYMENT', 'Pago de Examen Visual'), ('PAYMENT_RECEIVED', 'Cobro a Cliente'), ('ADVANCE_PAYMENT', 'Anticipo de Cliente'), ('REFUND', 'Devolución de Proveedor'), ('OTHER_INCOME', 'Otro Ingreso'), ('PURCHASE', 'Compra de Mercancía'), ('PURCHASE_FRAMES', 'Compra de Monturas'), ('PURCHASE_LENSES', 'Compra de Lentes'), ('PURCHASE_CONTACTS', 'Compra de Lentes de Contacto'), ('PAYMENT_MADE', 'Pago a Proveedor'), ('SALARY', 'Pago de Nómina'), ('RENT', 'Pago de Arriendo'), ('UTILITIES', 'Servicios Públicos'), ('MAINTENANCE', 'Mantenimiento de Equipos'), ('MARKETING', 'Publicidad y Marketing'), ('OFFICE_SUPPLIES', 'Útiles de Oficina'), ('CLEANING', 'Artículos de Limpieza'), ('TRANSPORT', 'Transporte y Envíos'), ('TAXES', 'Impuestos'), ('BANK_FEES', 'Comisiones Bancarias'), ('EXPENSE', 'Gasto Operativo'), ('REFUND_CUSTOMER', 'Devolución a Cliente'), ('WITHDRAWAL', 'Retiro de Efectivo'), ('OTHER_EXPENSE', 'Otro Egreso'), ('OPENING', 'Apertura de Caja'), ('CLOSURE', 'Cierre de Caja')], max_length=20, verbose_name='Categoría'),
        ),
    ]
