# Generated by Django 5.2.8 on 2026-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0003_cashcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashclosure',
            name='denomination_breakdown',
            field=models.TextField(blank=True, default='{}', verbose_name='Desglose de Denominaciones'),
        ),
    ]
