# Generated by Django 5.2.8 on 2026-01-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0004_alter_cashclosure_denomination_breakdown'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashclosure',
            unique_together=set(),
        ),
    ]
