# Generated by Django 3.2.25 on 2026-01-08 23:48

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0025_alter_organization_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('document_type', models.CharField(choices=[('image', 'Imagen'), ('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Hash MD5')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del objeto')),
                ('tags', apps.documents.models.JSONFieldCompatible(default=dict, help_text='Lista de etiquetas para búsqueda', verbose_name='Etiquetas')),
                ('metadata', apps.documents.models.JSONFieldCompatible(default=dict, help_text='Información adicional del archivo', verbose_name='Metadatos')),
                ('is_public', models.BooleanField(default=False, help_text='Visible para todos los usuarios de la org', verbose_name='Es público')),
                ('is_protected', models.BooleanField(default=False, help_text='No se puede eliminar', verbose_name='Protegido')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('download_count', models.IntegerField(default=0, verbose_name='Descargas')),
                ('view_count', models.IntegerField(default=0, verbose_name='Visualizaciones')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#3B82F6', help_text='Color en formato hex (#RRGGBB)', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='folder', help_text='Nombre del ícono', max_length=50, verbose_name='Ícono')),
                ('is_system', models.BooleanField(default=False, verbose_name='Es del sistema')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='organizations.organization', verbose_name='Organización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.folder', verbose_name='Carpeta padre')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(blank=True, max_length=254, verbose_name='Email destinatario')),
                ('public_link', models.CharField(blank=True, help_text='Token único para acceso público', max_length=100, null=True, unique=True, verbose_name='Enlace público')),
                ('can_view', models.BooleanField(default=True, verbose_name='Puede ver')),
                ('can_download', models.BooleanField(default=True, verbose_name='Puede descargar')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Puede editar')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('password', models.CharField(blank=True, help_text='Contraseña para acceder (hash)', max_length=128, verbose_name='Contraseña')),
                ('access_count', models.IntegerField(default=0, verbose_name='Accesos')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='Documento')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_shared', to=settings.AUTH_USER_MODEL, verbose_name='Compartido por')),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_received', to=settings.AUTH_USER_MODEL, verbose_name='Compartido con')),
            ],
            options={
                'verbose_name': 'Compartir documento',
                'verbose_name_plural': 'Documentos compartidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document', verbose_name='Documento')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.documentcomment', verbose_name='Comentario padre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Subido'), ('view', 'Visto'), ('download', 'Descargado'), ('edit', 'Editado'), ('delete', 'Eliminado'), ('share', 'Compartido'), ('comment', 'Comentado')], max_length=20, verbose_name='Acción')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.document', verbose_name='Documento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de documento',
                'verbose_name_plural': 'Actividades de documento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder', verbose_name='Carpeta'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.document', verbose_name='Documento padre'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['organization', 'parent'], name='documents_f_organiz_ea2118_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('organization', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_ef24f6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_252121_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'folder', '-created_at'], name='documents_d_organiz_371c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', '-created_at'], name='documents_d_documen_048969_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_d_file_ha_a7f76e_idx'),
        ),
    ]
