# Generated by Django 3.2.25 on 2026-01-03 22:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0023_alter_organizationmember_role'),
        ('patients', '0029_add_additional_refraction_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de promoción (ej: NAVIDAD2026)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo de la promoción', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada de la promoción')),
                ('discount_percentage', models.IntegerField(help_text='Porcentaje de descuento (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('frames', 'Monturas'), ('lenses', 'Lentes'), ('sunglasses', 'Gafas de Sol'), ('contacts', 'Lentes de Contacto'), ('exam', 'Examen Visual'), ('all', 'Todos los Productos')], default='all', max_length=20)),
                ('start_date', models.DateField(help_text='Fecha de inicio de la promoción')),
                ('end_date', models.DateField(help_text='Fecha de fin de la promoción')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('max_uses', models.IntegerField(blank=True, help_text='Máximo de veces que se puede usar (dejar vacío para ilimitado)', null=True)),
                ('current_uses', models.IntegerField(default=0, help_text='Veces que se ha usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la campaña', max_length=200)),
                ('message_template', models.TextField(help_text='Plantilla del mensaje. Variables: {name}, {code}, {discount}, {category}, {end_date}')),
                ('recipient_filter', models.CharField(choices=[('all', 'Todos los Clientes'), ('last_visit_30', 'Última visita hace 30 días'), ('last_visit_60', 'Última visita hace 60 días'), ('last_visit_90', 'Última visita hace 90 días'), ('last_visit_180', 'Última visita hace 6 meses'), ('never_visited', 'Nunca han visitado'), ('has_phone', 'Solo con teléfono registrado')], default='all', max_length=30)),
                ('daily_limit', models.IntegerField(default=20, help_text='Máximo de mensajes por día (recomendado: 20-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('delay_seconds', models.IntegerField(default=10, help_text='Segundos de espera entre mensajes (recomendado: 8-15)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('send_hour_start', models.IntegerField(default=9, help_text='Hora de inicio de envíos (formato 24h)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('send_hour_end', models.IntegerField(default=19, help_text='Hora de fin de envíos (formato 24h)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('in_progress', 'En Progreso'), ('paused', 'Pausada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Fecha programada de inicio', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_failed', models.IntegerField(default=0)),
                ('messages_pending', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_campaigns', to='organizations.organization')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Campaña de Promoción',
                'verbose_name_plural': 'Campañas de Promoción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Número de factura o referencia', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='patients.patient')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Uso de Promoción',
                'verbose_name_plural': 'Usos de Promociones',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(help_text='Texto del mensaje personalizado')),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('send_attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='promotions.promotioncampaign')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_messages', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Mensaje de Promoción',
                'verbose_name_plural': 'Mensajes de Promoción',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotionmessage',
            index=models.Index(fields=['campaign', 'status'], name='promotions__campaig_b87257_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionmessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='promotions__status_120c0b_idx'),
        ),
    ]
