# Generated by Django 3.2.25 on 2026-01-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_add_scheduled_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotioncampaign',
            name='scheduled_datetime',
        ),
    ]
