# Generated by Django 3.2.25 on 2025-12-10 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wompi_token_id', models.CharField(max_length=255, unique=True)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_brand', models.CharField(max_length=50)),
                ('card_type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], default='CREDIT', max_length=10)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('subscription_payment', 'Pago de Suscripción'), ('subscription_renewal', 'Renovación de Suscripción'), ('refund', 'Reembolso')], default='subscription_payment', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('DECLINED', 'Rechazada'), ('VOIDED', 'Anulada'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('wompi_reference', models.CharField(blank=True, max_length=255)),
                ('wompi_payment_method_type', models.CharField(blank=True, max_length=50)),
                ('wompi_payment_link_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paymentmethod')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRenewalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('pending', 'Pendiente'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('amount_attempted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_logs', to='users.usersubscription')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.transaction')),
            ],
            options={
                'verbose_name': 'Log de Renovación',
                'verbose_name_plural': 'Logs de Renovación',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='users_trans_created_f34d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='users_trans_status_efc2db_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wompi_transaction_id'], name='users_trans_wompi_t_9948f2_idx'),
        ),
    ]
