# Generated by Django 3.2.25 on 2025-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverificationtoken_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Indica si está en período de prueba gratuito', verbose_name='En Período de Prueba'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_converted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el trial se convirtió a suscripción pagada', null=True, verbose_name='Fecha de Conversión'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que termina el trial (solo para plan Free)', null=True, verbose_name='Fin del Período de Prueba'),
        ),
    ]
