# Generated by Django 5.2.8 on 2026-01-07 15:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0014_add_factura_electronica_fields'),
        ('organizations', '0025_alter_organization_owner'),
        ('sales', '0004_cascade_delete_on_user_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('expiration_date', models.DateField(blank=True, help_text='Opcional para productos no perecederos', null=True, verbose_name='Fecha de Vencimiento')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Unitario')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='sales.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN_PURCHASE', 'Entrada por compra'), ('IN_RETURN', 'Entrada por devolución'), ('IN_ADJUSTMENT', 'Entrada por ajuste'), ('IN_TRANSFER', 'Entrada por transferencia'), ('OUT_SALE', 'Salida por venta'), ('OUT_LOSS', 'Salida por pérdida'), ('OUT_DAMAGE', 'Salida por daño'), ('OUT_ADJUSTMENT', 'Salida por ajuste'), ('OUT_TRANSFER', 'Salida por transferencia')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total')),
                ('reference_document', models.CharField(blank=True, help_text='Factura, OC, Guía, etc.', max_length=100, verbose_name='Documento de Referencia')),
                ('reason', models.TextField(blank=True, help_text='Motivo del movimiento', verbose_name='Razón/Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('stock_before', models.IntegerField(default=0, verbose_name='Stock Anterior')),
                ('stock_after', models.IntegerField(default=0, verbose_name='Stock Posterior')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='sales.product', verbose_name='Producto')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.productlot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Stock Bajo'), ('OUT_OF_STOCK', 'Sin Stock'), ('NEAR_EXPIRY', 'Próximo a Vencer'), ('EXPIRED', 'Vencido'), ('OVERSTOCK', 'Sobrestock')], max_length=20, verbose_name='Tipo de Alerta')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10, verbose_name='Prioridad')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.productlot', verbose_name='Lote')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='sales.product', verbose_name='Producto')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Ajuste')),
                ('adjustment_type', models.CharField(choices=[('COUNT', 'Conteo Físico'), ('DAMAGE', 'Daño/Pérdida'), ('CORRECTION', 'Corrección'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Ajuste')),
                ('quantity_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Anterior')),
                ('quantity_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Después')),
                ('difference', models.IntegerField(default=0, verbose_name='Diferencia')),
                ('reason', models.TextField(verbose_name='Razón del Ajuste')),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impacto en Costo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='sales.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='inventory_i_organiz_e26b20_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productlot',
            index=models.Index(fields=['organization', 'product', 'is_active'], name='inventory_p_organiz_8e2d68_idx'),
        ),
        migrations.AddIndex(
            model_name='productlot',
            index=models.Index(fields=['expiration_date'], name='inventory_p_expirat_41333e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productlot',
            unique_together={('organization', 'product', 'lot_number')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['organization', 'product', '-created_at'], name='inventory_i_organiz_692c68_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['organization', 'movement_type', '-created_at'], name='inventory_i_organiz_09a1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['organization', 'is_resolved', '-created_at'], name='inventory_s_organiz_230747_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='inventory_s_alert_t_692cc6_idx'),
        ),
    ]
