"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key-2025')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Configuraciones de seguridad para producción (Contabo)
if not DEBUG:
    # Configuración de proxy SSL si se usa un proxy reverso (nginx, etc.)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Descomentar cuando se configure SSL en Contabo
    # SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF trusted origins - Lee de .env o usa defaults
csrf_origins_str = config('CSRF_TRUSTED_ORIGINS', default='')
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS = csrf_origins_str.split(',')
else:
    # Fallback a valores por defecto
    CSRF_TRUSTED_ORIGINS = [
        'https://optikaapp.com',
        'https://www.optikaapp.com',
        'https://demo.optikaapp.com',
        'http://www.optikaapp.com',
        'http://optikaapp.com',
        'http://84.247.129.180',
        'http://127.0.0.1:8000',
        'http://127.0.0.1:8001',
        'http://localhost:8000',
        'http://localhost:8001',
    ]


# Application definition

INSTALLED_APPS = [
    'daphne',  # Debe estar primero
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Para formateo de números (intcomma)
    
    # Third party apps
    'channels',
    'rest_framework',
    'corsheaders',
    'django_filters',
    
    # Local apps
    'apps.core',  # Utilidades compartidas
    'apps.organizations',
    'apps.permissions',  # Sistema de roles y permisos
    'apps.notifications',  # Sistema de notificaciones multi-canal
    'apps.audit',  # Sistema de auditoría y trazabilidad
    'apps.settings',  # Sistema de configuraciones dinámicas
    'apps.reports',  # Sistema de reportes y analytics
    'apps.documents',  # Gestión de documentos y archivos
    'apps.api',  # API REST completa con autenticación y webhooks
    'apps.tasks',  # Sistema de gestión de tareas y seguimiento
    'apps.workflows',  # Sistema de flujos de trabajo automatizados
    'apps.appointments',
    'apps.patients',
    'apps.users',
    'apps.dashboard',
    'apps.admin_dashboard',
    'apps.public',
    'apps.sales',
    'apps.billing',  # Facturación electrónica y pagos
    'apps.promotions',  # Sistema de promociones y campañas de marketing
    'apps.payroll',  # Nómina electrónica DIAN
    'apps.inventory',  # Gestión avanzada de inventario
    'apps.cash_register',  # Gestión de Caja y Tesorería
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise para archivos estáticos
    'apps.organizations.media_middleware.MediaFileMiddleware',  # Servir archivos de media en desarrollo con ASGI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.organizations.middleware.TenantMiddleware',  # Multi-tenant support
    'apps.users.email_verification_middleware.EmailVerificationMiddleware',  # Email verification
    'apps.organizations.middleware.SubscriptionMiddleware',  # Subscription validation
    'apps.organizations.middleware.PlanLimitsMiddleware',  # Plan limits and info
    'apps.organizations.middleware.PlanFeatureMiddleware',  # Feature access control
    'apps.organizations.middleware.LimitEnforcementMiddleware',  # Resource creation limits
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.audit.middleware.AuditMiddleware',  # Captura info de requests para auditoría
    'apps.audit.middleware.ErrorCaptureMiddleware',  # Monitoreo de errores (similar a Sentry)
]

# Configurar Whitenoise para NO servir archivos de MEDIA en desarrollo
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.dashboard.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

import dj_database_url

# Usar PostgreSQL en producción (Render), SQLite en desarrollo
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
    # Configuración SSL para PostgreSQL
    # Render requiere SSL para conexiones a la base de datos
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
        'connect_timeout': 10,
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Authentication backends
AUTHENTICATION_BACKENDS = [
    'apps.users.auth_backends.EmailOrUsernameBackend',  # Login con email o username
    'django.contrib.auth.backends.ModelBackend',  # Fallback por defecto
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = False  # Deshabilitado para usar formatos personalizados

USE_TZ = True

# Formatos de fecha personalizados (sobrescribir formatos locales)
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
SHORT_DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%d/%m/%Y', '%d-%m-%Y']
DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M', '%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'apps' / 'dashboard' / 'static',
    BASE_DIR / 'apps' / 'public' / 'static',
]

# Whitenoise para servir archivos estáticos en producción (solo si no es DEBUG)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==================== CONFIGURACIÓN DE ARCHIVOS MEDIA ====================
# En desarrollo: archivos locales
# En producción (Render): disco persistente montado

MEDIA_URL = '/media/'

# Configuración de almacenamiento de medios
if DEBUG:
    # Desarrollo: usar carpeta local
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # Producción en Render: usar disco persistente
    # El disco persistente se monta en /opt/render/project/src/media_storage
    # Debes crear un Render Disk y montarlo en esta ruta
    RENDER_MEDIA_PATH = config('RENDER_MEDIA_PATH', default='/opt/render/project/src/media_storage')
    MEDIA_ROOT = RENDER_MEDIA_PATH

# URL de medios de producción (Render) para desarrollo local
# Si usas base de datos de producción pero archivos locales, los archivos que no existan
# localmente se cargarán desde esta URL
PRODUCTION_MEDIA_URL = config('PRODUCTION_MEDIA_URL', default='https://opticaapp.onrender.com/media/')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Appointment Settings
APPOINTMENT_SLOT_DURATION = config('APPOINTMENT_SLOT_DURATION', default=30, cast=int)
MAX_DAILY_APPOINTMENTS = config('MAX_DAILY_APPOINTMENTS', default=20, cast=int)
ADVANCE_BOOKING_DAYS = config('ADVANCE_BOOKING_DAYS', default=30, cast=int)

# Login Settings
LOGIN_URL = '/dashboard/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/dashboard/login/'

# Channels Configuration
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# ==================== NOTIFICACIONES ====================

# Sistema de Notificaciones (Auto-detecta entorno)
# False = WhatsApp Local (Desarrollo)
# True = Email (Producción - Gratis)
USE_EMAIL_NOTIFICATIONS = config('USE_EMAIL_NOTIFICATIONS', default=not DEBUG, cast=bool)

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='compueasys@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='hucewtoa stbqrcnk')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=f'OpticaApp <{config("EMAIL_HOST_USER", default="compueasys@gmail.com")}>')
CONTACT_EMAIL = config('CONTACT_EMAIL', default=config('EMAIL_HOST_USER', default='compueasys@gmail.com'))
EMAIL_TIMEOUT = 30

# WhatsApp Configuration (Local Bot - Gratuito)
WHATSAPP_API_URL = config('WHATSAPP_API_URL', default='http://localhost:3000')

# Twilio WhatsApp Configuration (Opcional - de pago)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = config('TWILIO_WHATSAPP_FROM', default='whatsapp:+14155238886')  # Twilio Sandbox

# Business Information
BUSINESS_PHONE = config('BUSINESS_PHONE', default='300 123 4567')
WEBSITE_URL = config('WEBSITE_URL', default='http://127.0.0.1:8000')

# ==================== WOMPI PAYMENT GATEWAY ====================

# Wompi Configuration
WOMPI_PUBLIC_KEY = config('WOMPI_PUBLIC_KEY', default='pub_prod_DMT4tAPNSvnvuHiVmwjIoyVwaam8N3k7')
WOMPI_PRIVATE_KEY = config('WOMPI_PRIVATE_KEY', default='prv_prod_1X63CjcbCvba86WpWJOuXiqJnKvtMgeT')
WOMPI_EVENTS_SECRET = config('WOMPI_EVENTS_SECRET', default='prod_events_cmDhDmWt3heMjSm5uB9QMRHJO8HxJLvv')
WOMPI_INTEGRITY_SECRET = config('WOMPI_INTEGRITY_SECRET', default='prod_integrity_YW2t43XJOhLUAOONX5u6U8AO5sEosmTT')
WOMPI_BASE_URL = config('WOMPI_BASE_URL', default='https://production.wompi.co/v1')
WOMPI_TEST_MODE = config('WOMPI_TEST_MODE', default=False, cast=bool)

# ==================== CURRENCY CONFIGURATION ====================
# Tasa de cambio USD a COP (actualizar según necesites)
USD_TO_COP_RATE = config('USD_TO_COP_RATE', default=4000.00, cast=float)
CURRENCY_DISPLAY = config('CURRENCY_DISPLAY', default='COP')  # COP, USD, BOTH

# ==================== WHATSAPP BAILEYS SERVER ====================
WHATSAPP_SERVER_URL = config('WHATSAPP_SERVER_URL', default='http://localhost:3000')
WHATSAPP_SERVER_API_KEY = config('WHATSAPP_SERVER_API_KEY', default='')

# ==================== NOMINA ELECTRONICA - DIAN ====================

# Certificado Digital (.p12 o .pfx) para firma electrónica
# Debe estar en un directorio seguro fuera del repositorio
PAYROLL_CERTIFICATE_PATH = config('PAYROLL_CERTIFICATE_PATH', default='')
PAYROLL_CERTIFICATE_PASSWORD = config('PAYROLL_CERTIFICATE_PASSWORD', default='')

# Configuración DIAN (Software ID y PIN obtenidos después de registro)
DIAN_SOFTWARE_ID = config('DIAN_SOFTWARE_ID', default='')
DIAN_SOFTWARE_PIN = config('DIAN_SOFTWARE_PIN', default='')
DIAN_TEST_SET_ID = config('DIAN_TEST_SET_ID', default='')  # Para ambiente de pruebas

# Modo de pruebas (True: Habilitación, False: Producción)
DIAN_TEST_MODE = config('DIAN_TEST_MODE', default=True, cast=bool)

# ==================== REST FRAMEWORK (API) ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.api.authentication.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'apps.api.throttling.APIKeyRateThrottle',
        'apps.api.throttling.IPRateThrottle',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}
