# Generated by Django 3.2.25 on 2026-01-08 23:17

import apps.settings.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Identificador único (ej: email.smtp_host)', max_length=200, verbose_name='Clave')),
                ('value', models.TextField(blank=True, help_text='Valor de la configuración', verbose_name='Valor')),
                ('value_type', models.CharField(choices=[('string', 'Texto'), ('int', 'Número entero'), ('float', 'Número decimal'), ('bool', 'Booleano'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL'), ('color', 'Color'), ('date', 'Fecha'), ('datetime', 'Fecha y hora')], default='string', max_length=20, verbose_name='Tipo de valor')),
                ('module', models.CharField(blank=True, db_index=True, help_text='Módulo al que pertenece (appointments, billing, etc.)', max_length=50, verbose_name='Módulo')),
                ('description', models.TextField(blank=True, help_text='Descripción de la configuración', verbose_name='Descripción')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marcar si es API key, password, etc.', verbose_name='Es sensible')),
                ('validation_rule', models.CharField(blank=True, help_text='Expresión regular, rango, etc.', max_length=500, verbose_name='Regla de validación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('default_value', models.TextField(blank=True, verbose_name='Valor por defecto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('organization', models.ForeignKey(blank=True, help_text='Dejar vacío para configuración global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['module', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SettingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de ícono (ej: fas fa-cog)', max_length=50, verbose_name='Ícono')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('settings', models.ManyToManyField(blank=True, related_name='categories', to='settings.AppSetting', verbose_name='Configuraciones')),
            ],
            options={
                'verbose_name': 'Categoría de configuración',
                'verbose_name_plural': 'Categorías de configuración',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('payment', 'Pagos'), ('dian', 'DIAN (Facturación electrónica)'), ('erp', 'ERP'), ('crm', 'CRM'), ('analytics', 'Analytics'), ('storage', 'Almacenamiento'), ('other', 'Otro')], db_index=True, max_length=50, verbose_name='Tipo de integración')),
                ('name', models.CharField(help_text='Nombre del servicio (ej: Wompi, Twilio, SMTP)', max_length=100, verbose_name='Nombre')),
                ('config', apps.settings.models.JSONFieldCompatible(default=dict, help_text='Configuración en formato JSON', verbose_name='Configuración')),
                ('credentials', apps.settings.models.JSONFieldCompatible(default=dict, help_text='API keys, tokens, passwords (se deben encriptar)', verbose_name='Credenciales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Si está en modo sandbox/test', verbose_name='Modo de prueba')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Última vez que se verificó la conexión', null=True, verbose_name='Última verificación')),
                ('is_verified', models.BooleanField(default=False, help_text='Si la conexión fue verificada exitosamente', verbose_name='Verificado')),
                ('verification_error', models.TextField(blank=True, verbose_name='Error de verificación')),
                ('metadata', apps.settings.models.JSONFieldCompatible(default=dict, help_text='Información adicional', verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración de integración',
                'verbose_name_plural': 'Configuraciones de integración',
                'ordering': ['integration_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['integration_type', 'is_active'], name='settings_in_integra_5ed09f_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['organization', 'is_active'], name='settings_in_organiz_e1e161_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('integration_type', 'name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='appsetting',
            index=models.Index(fields=['key', 'organization'], name='settings_ap_key_33b654_idx'),
        ),
        migrations.AddIndex(
            model_name='appsetting',
            index=models.Index(fields=['module', 'is_active'], name='settings_ap_module_0f74b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appsetting',
            unique_together={('key', 'organization')},
        ),
    ]
