# Generated by Django 3.2.25 on 2025-12-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_phone_n_933975_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_identif_6b6f1c_idx',
        ),
        migrations.AddField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identificación'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('organization', 'identification')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'phone_number'], name='patients_pa_organiz_35f9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'identification'], name='patients_pa_organiz_cffffc_idx'),
        ),
    ]
