# Generated by Django 3.2.25 on 2025-12-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20251201_1849'),
        ('patients', '0002_patient_optics_fields'),
    ]

    operations = [
    ]
