# Generated by Django 3.2.25 on 2025-12-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20251201_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='companion_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del acompañante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='companion_phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Teléfono del acompañante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='companion_relationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relación con el paciente'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_companion',
            field=models.BooleanField(default=False, verbose_name='Viene con acompañante'),
        ),
    ]
