# Generated by Django 3.2.25 on 2025-12-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_neighborhood'),
        ('patients', '0005_auto_20251202_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('identification', models.CharField(max_length=50, unique=True, verbose_name='Cédula/ID')),
                ('specialty', models.CharField(choices=[('optometrist', 'Optometrista'), ('ophthalmologist', 'Oftalmólogo'), ('general', 'Médico General'), ('other', 'Otro')], default='optometrist', max_length=50, verbose_name='Especialidad')),
                ('professional_card', models.CharField(blank=True, max_length=50, verbose_name='Tarjeta Profesional')),
                ('rethus', models.CharField(blank=True, help_text='Registro Único Nacional del Talento Humano en Salud', max_length=50, verbose_name='Registro RETHUS')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Graduación')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Universidad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('monday_schedule', models.CharField(blank=True, help_text='Ej: 8:00-12:00, 14:00-18:00', max_length=100, verbose_name='Lunes')),
                ('tuesday_schedule', models.CharField(blank=True, max_length=100, verbose_name='Martes')),
                ('wednesday_schedule', models.CharField(blank=True, max_length=100, verbose_name='Miércoles')),
                ('thursday_schedule', models.CharField(blank=True, max_length=100, verbose_name='Jueves')),
                ('friday_schedule', models.CharField(blank=True, max_length=100, verbose_name='Viernes')),
                ('saturday_schedule', models.CharField(blank=True, max_length=100, verbose_name='Sábado')),
                ('sunday_schedule', models.CharField(blank=True, max_length=100, verbose_name='Domingo')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='doctors/signatures/', verbose_name='Firma Digital')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, help_text='Breve descripción profesional', verbose_name='Biografía')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Doctor/Optómetra',
                'verbose_name_plural': 'Doctores/Optómetras',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['organization', 'is_active'], name='patients_do_organiz_75289f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['professional_card'], name='patients_do_profess_f79f0f_idx'),
        ),
    ]
