# Generated by Django 3.2.25 on 2025-12-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20251202_1909'),
    ]

    operations = [
        # Paso 1: Hacer el campo nullable primero
        migrations.AlterField(
            model_name='clinicalhistory',
            name='doctor',
            field=models.CharField(max_length=200, verbose_name='Médico/Optómetra', blank=True, null=True),
        ),
        
        # Paso 2: Eliminar la columna antigua
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='doctor',
        ),
        
        # Paso 3: Agregar la nueva columna como ForeignKey
        migrations.AddField(
            model_name='clinicalhistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_histories', to='patients.doctor', verbose_name='Médico/Optómetra'),
        ),
    ]
