# Generated by Django 3.2.25 on 2025-12-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20251202_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_histories', to='patients.doctor', verbose_name='Médico/Optómetra'),
        ),
    ]
