# Generated by Django 3.2.25 on 2025-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_clinicalhistory_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('NIT', 'NIT'), ('OTRO', 'Otro')], default='CC', max_length=10, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('optometrist', 'Optómetra'), ('ophthalmologist', 'Oftalmólogo'), ('general', 'Médico General'), ('other', 'Otro')], default='optometrist', max_length=50, verbose_name='Especialidad'),
        ),
    ]
