# Generated by Django 3.2.25 on 2025-12-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20251203_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('NIT', 'NIT'), ('OTRO', 'Otro')], default='CC', max_length=10, verbose_name='Tipo de identificación'),
        ),
    ]
