# Generated by Django 3.2.25 on 2025-12-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_doctor_identification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='biomicroscopy_od_pupil',
            field=models.TextField(blank=True, help_text='Tamaño, forma, reactividad', verbose_name='OD Pupila'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='biomicroscopy_os_pupil',
            field=models.TextField(blank=True, help_text='Tamaño, forma, reactividad', verbose_name='OS Pupila'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='clinical_summary',
            field=models.TextField(blank=True, help_text='Resumen ejecutivo del caso', verbose_name='Resumen de Historia Clínica'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='complementary_exams',
            field=models.TextField(blank=True, help_text='OCT, Campo Visual, Topografía, etc.', verbose_name='Exámenes Complementarios'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='counter_referral',
            field=models.TextField(blank=True, help_text='Respuesta de especialista', verbose_name='Contrarremisión'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_clinical_condition',
            field=models.TextField(blank=True, verbose_name='Condición Clínica Actual'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegia_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento Cicloplejia Firmado'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegia_consent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Consentimiento Cicloplejia'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='differential_diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnóstico Diferencial'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='disposition',
            field=models.TextField(blank=True, help_text='Plan inmediato y manejo', verbose_name='Disposición'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='evolution_notes',
            field=models.TextField(blank=True, help_text='Notas de evolución del paciente', verbose_name='Evolución'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='external_exam_od',
            field=models.TextField(blank=True, help_text='Anexos oculares, órbita, etc.', verbose_name='Examen Externo OD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='external_exam_os',
            field=models.TextField(blank=True, verbose_name='Examen Externo OS'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='fundoscopy_od_cup_disc_ratio',
            field=models.CharField(blank=True, help_text='Ej: 0.3', max_length=10, verbose_name='OD Relación Copa/Disco'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='fundoscopy_od_retina',
            field=models.TextField(blank=True, verbose_name='OD Retina'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='fundoscopy_os_cup_disc_ratio',
            field=models.CharField(blank=True, help_text='Ej: 0.3', max_length=10, verbose_name='OS Relación Copa/Disco'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='fundoscopy_os_retina',
            field=models.TextField(blank=True, verbose_name='OS Retina'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='lab_orders',
            field=models.TextField(blank=True, verbose_name='Órdenes de Laboratorio'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='medical_certificate',
            field=models.TextField(blank=True, verbose_name='Certificaciones Médicas'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Enfermedades sistémicas, cirugías previas, etc.', verbose_name='Antecedentes Médicos'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='prognosis',
            field=models.TextField(blank=True, verbose_name='Pronóstico'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='referral_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de Remisión'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='referral_to',
            field=models.CharField(blank=True, help_text='Especialista o institución', max_length=200, verbose_name='Remisión a'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='remission_document',
            field=models.TextField(blank=True, verbose_name='Documento de Remisión'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='specialized_exam_orders',
            field=models.TextField(blank=True, help_text='OCT, Campo Visual, etc.', verbose_name='Órdenes de Exámenes Especializados'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='surgical_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento Quirúrgico Firmado'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='surgical_consent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Consentimiento Quirúrgico'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='chief_complaint',
            field=models.TextField(blank=True, verbose_name='Motivo de Consulta (MC)'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='current_illness',
            field=models.TextField(blank=True, verbose_name='Enfermedad Actual (EA)'),
        ),
    ]
