# Generated by Django 3.2.25 on 2025-12-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20251203_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='adjuvant_therapies',
            field=models.TextField(blank=True, help_text='Terapias complementarias, ejercicios visuales, etc.', verbose_name='Terapias Coadyuvantes'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='optical_prescription_notes',
            field=models.TextField(blank=True, help_text='Detalles adicionales sobre la prescripción óptica', verbose_name='Notas de Prescripción Óptica'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='pharmaceutical_prescription',
            field=models.TextField(blank=True, help_text='Medicamentos recetados: nombre, dosis, vía, frecuencia, duración', verbose_name='Prescripción Farmacéutica'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='topical_medication_protocol',
            field=models.TextField(blank=True, help_text='Gotas, ungüentos, lubricantes oculares', verbose_name='Protocolo Fármacos Tópicos Oftálmicos'),
        ),
    ]
