# Generated by Django 3.2.25 on 2025-12-04 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_auto_20251203_1942'),
        ('patients', '0011_auto_20251203_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('medication', 'Medicamento'), ('topical_medication', 'Medicamento Tópico Oftálmico'), ('systemic_medication', 'Medicamento Sistémico'), ('lens_type', 'Tipo de Lentes'), ('lens_material', 'Material de Lentes'), ('lens_coating', 'Tratamiento/Recubrimiento'), ('lens_brand', 'Marca de Lentes'), ('frame_type', 'Tipo de Montura'), ('contact_lens_type', 'Tipo de Lentes de Contacto'), ('contact_lens_brand', 'Marca de Lentes de Contacto'), ('contact_lens_material', 'Material de LC'), ('contact_lens_wearing', 'Régimen de Uso LC'), ('diagnosis', 'Diagnóstico'), ('diagnosis_category', 'Categoría de Diagnóstico'), ('treatment', 'Tratamiento'), ('therapy', 'Terapia Coadyuvante'), ('visual_therapy', 'Terapia Visual'), ('complementary_exam', 'Examen Complementario'), ('lab_test', 'Examen de Laboratorio'), ('recommendation', 'Recomendación'), ('referral_specialty', 'Especialidad para Remisión'), ('follow_up_reason', 'Motivo de Seguimiento')], db_index=True, max_length=50, verbose_name='Tipo de Parámetro')),
                ('name', models.CharField(help_text='Nombre del parámetro', max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, help_text='Código o abreviatura (opcional)', max_length=50, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada o instrucciones', verbose_name='Descripción')),
                ('dosage', models.CharField(blank=True, help_text='Dosis estándar (ej: 1 gota cada 8 horas)', max_length=200, verbose_name='Dosis')),
                ('administration_route', models.CharField(blank=True, choices=[('topical', 'Tópico'), ('oral', 'Oral'), ('parenteral', 'Parenteral'), ('sublingual', 'Sublingual'), ('other', 'Otro')], max_length=50, verbose_name='Vía de Administración')),
                ('frequency', models.CharField(blank=True, help_text='Frecuencia de uso (ej: cada 8 horas, 3 veces al día)', max_length=200, verbose_name='Frecuencia')),
                ('duration', models.CharField(blank=True, help_text='Duración del tratamiento (ej: 7 días, 2 semanas)', max_length=100, verbose_name='Duración')),
                ('icd_10_code', models.CharField(blank=True, help_text='Código internacional de enfermedades', max_length=20, verbose_name='Código CIE-10')),
                ('category', models.CharField(blank=True, help_text='Categoría o especialidad', max_length=100, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo aparecerá en los selectores', verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, help_text='Marcar como opción predeterminada', verbose_name='Predeterminado')),
                ('display_order', models.IntegerField(default=0, help_text='Orden en listas (menor número = primero)', verbose_name='Orden de Visualización')),
                ('usage_count', models.IntegerField(default=0, help_text='Contador de veces que se ha usado', verbose_name='Veces Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_parameters', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicalparameter_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Parámetro Clínico',
                'verbose_name_plural': 'Parámetros Clínicos',
                'ordering': ['parameter_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Protocolo')),
                ('protocol_type', models.CharField(choices=[('medication', 'Farmacológico'), ('optical', 'Óptico'), ('surgical', 'Quirúrgico'), ('visual_therapy', 'Terapia Visual'), ('combined', 'Combinado')], max_length=50, verbose_name='Tipo de Protocolo')),
                ('diagnosis_indication', models.CharField(help_text='Para qué diagnóstico está indicado', max_length=200, verbose_name='Indicación/Diagnóstico')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('phase_1', models.TextField(blank=True, help_text='Primera fase del tratamiento', verbose_name='Fase 1')),
                ('phase_2', models.TextField(blank=True, verbose_name='Fase 2')),
                ('phase_3', models.TextField(blank=True, verbose_name='Fase 3')),
                ('follow_up_schedule', models.TextField(blank=True, help_text='Cuándo y cómo hacer seguimiento', verbose_name='Cronograma de Seguimiento')),
                ('expected_duration', models.CharField(blank=True, max_length=100, verbose_name='Duración Esperada')),
                ('success_criteria', models.TextField(blank=True, help_text='Cómo evaluar el éxito del tratamiento', verbose_name='Criterios de Éxito')),
                ('contraindications', models.TextField(blank=True, verbose_name='Contraindicaciones')),
                ('precautions', models.TextField(blank=True, verbose_name='Precauciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Veces Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('medications', models.ManyToManyField(blank=True, limit_choices_to={'parameter_type__in': ['medication', 'topical_medication', 'systemic_medication', 'treatment']}, related_name='treatment_protocols', to='patients.ClinicalParameter', verbose_name='Medicamentos/Tratamientos')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatmentprotocol_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Protocolo de Tratamiento',
                'verbose_name_plural': 'Protocolos de Tratamiento',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpticalPrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Miopía Baja, Hipermetropía + Presbicia', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('recommendations', models.TextField(blank=True, help_text='Recomendaciones específicas para este tipo de prescripción', verbose_name='Recomendaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Veces Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_optical_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('lens_coatings', models.ManyToManyField(blank=True, limit_choices_to={'parameter_type': 'lens_coating'}, related_name='optical_templates', to='patients.ClinicalParameter', verbose_name='Tratamientos Recomendados')),
                ('lens_material', models.ForeignKey(blank=True, limit_choices_to={'parameter_type': 'lens_material'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_templates_by_material', to='patients.clinicalparameter', verbose_name='Material Recomendado')),
                ('lens_type', models.ForeignKey(blank=True, limit_choices_to={'parameter_type': 'lens_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_templates_by_type', to='patients.clinicalparameter', verbose_name='Tipo de Lentes')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opticalprescriptiontemplate_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Plantilla de Prescripción Óptica',
                'verbose_name_plural': 'Plantillas de Prescripción Óptica',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Tratamiento Conjuntivitis Bacteriana', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('diagnosis', models.CharField(blank=True, max_length=200, verbose_name='Diagnóstico Asociado')),
                ('prescription_text', models.TextField(help_text='Texto completo de la prescripción', verbose_name='Texto de Prescripción')),
                ('instructions', models.TextField(blank=True, help_text='Instrucciones adicionales para el paciente', verbose_name='Instrucciones')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='Duración (días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Veces Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medication_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('medications', models.ManyToManyField(blank=True, limit_choices_to={'parameter_type__in': ['medication', 'topical_medication', 'systemic_medication']}, related_name='medication_templates', to='patients.ClinicalParameter', verbose_name='Medicamentos')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicationtemplate_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Plantilla de Medicación',
                'verbose_name_plural': 'Plantillas de Medicación',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalparameter',
            index=models.Index(fields=['organization', 'parameter_type', 'is_active'], name='patients_cl_organiz_58eb20_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalparameter',
            index=models.Index(fields=['organization', 'is_active', 'display_order'], name='patients_cl_organiz_22625a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalparameter',
            unique_together={('organization', 'parameter_type', 'name')},
        ),
    ]
