# Generated by Django 5.2.8 on 2025-12-04 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20251203_1942'),
        ('patients', '0012_auto_20251203_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='allergic_history',
            field=models.TextField(blank=True, help_text='Alergias conocidas', verbose_name='Alérgicos'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='family_cancer',
            field=models.BooleanField(default=False, verbose_name='Cáncer (Familiar)'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='family_general_notes',
            field=models.TextField(blank=True, verbose_name='Notas Familiares Generales'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='family_heart_disease',
            field=models.BooleanField(default=False, verbose_name='Cardiopatías (Familiar)'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='family_myopia',
            field=models.BooleanField(default=False, verbose_name='Miopía (Familiar)'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='family_ocular_notes',
            field=models.TextField(blank=True, verbose_name='Notas Familiares Oculares'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='family_retinal_detachment',
            field=models.BooleanField(default=False, verbose_name='Desprendimiento de Retina (Familiar)'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='family_strabismus',
            field=models.BooleanField(default=False, verbose_name='Estrabismo (Familiar)'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='ocular_pathological_history',
            field=models.TextField(blank=True, verbose_name='Patológicos Oculares'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='ocular_pharmacological_history',
            field=models.TextField(blank=True, verbose_name='Farmacológicos Oculares'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='ocular_surgical_history',
            field=models.TextField(blank=True, verbose_name='Quirúrgicos Oculares'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='ocular_therapeutic_history',
            field=models.TextField(blank=True, verbose_name='Terapéuticos Oculares'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='ocular_trauma_history',
            field=models.TextField(blank=True, verbose_name='Traumatológicos Oculares'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='other_general_history',
            field=models.TextField(blank=True, verbose_name='Otros Generales'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='pathological_history',
            field=models.TextField(blank=True, help_text='Enfermedades crónicas, patologías', verbose_name='Patológicos'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='pharmacological_history',
            field=models.TextField(blank=True, help_text='Medicamentos actuales', verbose_name='Farmacológicos'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='surgical_history',
            field=models.TextField(blank=True, help_text='Cirugías previas generales', verbose_name='Quirúrgicos'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='trauma_history',
            field=models.TextField(blank=True, help_text='Traumatismos previos', verbose_name='Traumatológicos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='family_history_notes',
            field=models.TextField(blank=True, verbose_name='Notas Antecedentes Familiares (Legacy)'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Campo antiguo - usar los específicos', verbose_name='Antecedentes Médicos (Legacy)'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='clinicalhistoryattachment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='clinicalparameter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='medicationtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='opticalprescriptiontemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='treatmentprotocol',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización'),
        ),
    ]
