# Generated by Django 3.2.25 on 2025-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_clinicalhistory_allergic_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='distance_chart',
            field=models.CharField(blank=True, help_text='Cartilla utilizada para medir visión de lejos (ETDRS, Snellen, etc.)', max_length=50, verbose_name='Cartilla Visión Lejana'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='near_chart',
            field=models.CharField(blank=True, help_text='Cartilla utilizada para medir visión de cerca (Jaeger, Rosenbaum, etc.)', max_length=50, verbose_name='Cartilla Visión Próxima'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_od_cc_distance',
            field=models.CharField(blank=True, help_text='Ej: 20/20, 20/40, 6/6', max_length=20, verbose_name='AV OD CC Lejos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_od_cc_near',
            field=models.CharField(blank=True, help_text='Ej: J1, N5, a 40cm', max_length=20, verbose_name='AV OD CC Cerca'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_od_sc_distance',
            field=models.CharField(blank=True, help_text='Ej: 20/20, 20/40, 6/6', max_length=20, verbose_name='AV OD SC Lejos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_od_sc_near',
            field=models.CharField(blank=True, help_text='Ej: J1, N5, a 40cm', max_length=20, verbose_name='AV OD SC Cerca'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_os_cc_distance',
            field=models.CharField(blank=True, help_text='Ej: 20/20, 20/40, 6/6', max_length=20, verbose_name='AV OS CC Lejos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_os_cc_near',
            field=models.CharField(blank=True, help_text='Ej: J1, N5, a 40cm', max_length=20, verbose_name='AV OS CC Cerca'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_os_sc_distance',
            field=models.CharField(blank=True, help_text='Ej: 20/20, 20/40, 6/6', max_length=20, verbose_name='AV OS SC Lejos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_os_sc_near',
            field=models.CharField(blank=True, help_text='Ej: J1, N5, a 40cm', max_length=20, verbose_name='AV OS SC Cerca'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_ou_distance',
            field=models.CharField(blank=True, help_text='Ej: 20/20, 6/6', max_length=20, verbose_name='AV OU Lejos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='va_ou_near',
            field=models.CharField(blank=True, help_text='Ej: J1, a 40cm', max_length=20, verbose_name='AV OU Cerca'),
        ),
    ]
