# Generated by Django 3.2.25 on 2025-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20251204_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_od_sphere',
            field=models.CharField(blank=True, default='', help_text='Ej: +2.50, -1.25, N/A', max_length=10, verbose_name='OD Esfera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_os_sphere',
            field=models.CharField(blank=True, default='', help_text='Ej: +2.50, -1.25, N/A', max_length=10, verbose_name='OS Esfera'),
            preserve_default=False,
        ),
    ]
