# Generated by Django 3.2.25 on 2025-12-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='complementary_exam',
            field=models.TextField(blank=True, verbose_name='Exámenes Complementarios Solicitados'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='contact_lens_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca de LC'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='contact_lens_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Material de LC'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='contact_lens_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Lentes de Contacto'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='contact_lens_wearing',
            field=models.CharField(blank=True, max_length=100, verbose_name='Régimen de Uso LC'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='diagnosis_text',
            field=models.TextField(blank=True, verbose_name='Texto de Diagnóstico Detallado'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='frame_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Montura'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Recomendaciones Específicas'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='recommendations_text',
            field=models.TextField(blank=True, verbose_name='Texto de Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='referral_specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Remisión a Especialidad'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_od_dnp',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distancia Nasal-Pupilar OD', max_digits=4, null=True, verbose_name='OD DNP (mm)'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_od_sphere',
            field=models.CharField(blank=True, default=0.0, help_text='Ej: +2.50, -1.25, N/A', max_length=10, verbose_name='OD Esfera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_os_dnp',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distancia Nasal-Pupilar OS', max_digits=4, null=True, verbose_name='OS DNP (mm)'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_os_sphere',
            field=models.CharField(blank=True, default=0.0, help_text='Ej: +2.50, -1.25, N/A', max_length=10, verbose_name='OS Esfera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='therapy',
            field=models.TextField(blank=True, verbose_name='Terapias Coadyuvantes'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='visual_therapy',
            field=models.TextField(blank=True, verbose_name='Terapias Visuales'),
        ),
    ]
