# Generated by Django 3.2.25 on 2025-12-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20251210_1329'),
    ]

    operations = [
        # Esta migración está vacía intencionalmente
        # Los cambios en los campos ya se reflejan en el modelo
        # y se aplicarán automáticamente en futuras migraciones si es necesario
    ]
