# Generated by Django 3.2.25 on 2025-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_auto_20251218_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='last_eye_checkup',
            field=models.CharField(blank=True, help_text='Ej: Hace 1 año, Hace 6 meses, Primera vez, etc.', max_length=200, verbose_name='Tiempo del Último Control de Ojos'),
        ),
    ]
