# Generated by Django 3.2.25 on 2025-12-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_clinicalhistory_last_eye_checkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='lensometry_lens_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parameter_type': 'lens_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lensometry_histories', to='patients.clinicalparameter', verbose_name='Tipo de Lente (Lensometría)'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='lensometry_notes',
            field=models.TextField(blank=True, help_text='Mediciones de lentes actuales del paciente', verbose_name='Notas de Lensometría'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='ocular_therapeutic_history',
            field=models.TextField(blank=True, help_text='Campo antiguo - usar lensometría', verbose_name='Terapéuticos Oculares (Legacy)'),
        ),
    ]
