# Generated by Django 3.2.25 on 2025-12-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20251218_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Fórmula Actual OD ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_od_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fórmula Actual OD Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_od_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fórmula Actual OD Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_od_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fórmula Actual OD Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Fórmula Actual OS ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_os_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fórmula Actual OS Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_os_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fórmula Actual OS Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='current_rx_os_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fórmula Actual OS Esfera'),
        ),
    ]
