# Generated by Django 3.2.25 on 2025-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20251218_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='current_rx_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fórmula Actual OD ADD'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='current_rx_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fórmula Actual OS ADD'),
        ),
    ]
