# Generated by Django 3.2.25 on 2025-12-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_fix_add_field_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OD Adición'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OS Adición'),
        ),
    ]
