# Generated by Django 5.2.8 on 2025-12-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_add_new_navbar_styles'),
        ('patients', '0026_alter_colorvisiontest_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='identification',
            field=models.CharField(max_length=50, verbose_name='Cédula/ID'),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('organization', 'identification')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['organization', 'identification'], name='patients_do_organiz_39d5c6_idx'),
        ),
    ]
