# Generated by Django 5.2.8 on 2025-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_change_doctor_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='current_rx_od_sphere',
            field=models.CharField(blank=True, help_text='Ej: +2.00, -1.50, N, NLP', max_length=20, null=True, verbose_name='Fórmula Actual OD Esfera'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='current_rx_os_sphere',
            field=models.CharField(blank=True, help_text='Ej: +2.00, -1.50, N, NLP', max_length=20, null=True, verbose_name='Fórmula Actual OS Esfera'),
        ),
    ]
