# Generated by Django 5.2.8 on 2025-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_change_sphere_fields_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ciclopléjico OD ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_od_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ciclopléjico OD Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_od_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ciclopléjico OD Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_od_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciclopléjico OD Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ciclopléjico OS ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_os_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ciclopléjico OS Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_os_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ciclopléjico OS Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='cycloplegic_os_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciclopléjico OS Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='exam_cycloplegic_done',
            field=models.BooleanField(default=False, verbose_name='Subjetivo bajo Cicloplejia Realizado'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='exam_final_rx_done',
            field=models.BooleanField(default=False, verbose_name='RX Final Realizado'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='exam_refinement_done',
            field=models.BooleanField(default=False, verbose_name='Afinación Realizada'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='exam_retinoscopy_done',
            field=models.BooleanField(default=False, verbose_name='Retinoscopia Realizada'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='exam_subjective_done',
            field=models.BooleanField(default=False, verbose_name='Subjetivo Realizado'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='RX Final OD ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_od_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='RX Final OD Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_od_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='RX Final OD Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_od_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RX Final OD Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='RX Final OS ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_os_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='RX Final OS Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_os_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='RX Final OS Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='final_rx_os_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RX Final OS Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Afinación OD ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_od_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Afinación OD Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_od_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Afinación OD Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_od_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Afinación OD Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Afinación OS ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_os_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Afinación OS Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_os_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Afinación OS Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='refinement_os_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Afinación OS Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Retinoscopia OD ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_od_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Retinoscopia OD Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_od_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Retinoscopia OD Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_od_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Retinoscopia OD Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Retinoscopia OS ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_os_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Retinoscopia OS Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_os_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Retinoscopia OS Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='retinoscopy_os_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Retinoscopia OS Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Subjetivo OD ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_od_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subjetivo OD Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_od_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Subjetivo OD Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_od_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Subjetivo OD Esfera'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_os_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Subjetivo OS ADD'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_os_axis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subjetivo OS Eje'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_os_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Subjetivo OS Cilindro'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='subjective_os_sphere',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Subjetivo OS Esfera'),
        ),
    ]
