# Generated by Django 3.2.25 on 2026-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_add_additional_refraction_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_od_prism',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OD Prisma'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_od_sphere',
            field=models.CharField(blank=True, help_text='Ej: +2.50, -1.25, N/A', max_length=10, null=True, verbose_name='OD Esfera'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_os_prism',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OS Prisma'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='refraction_os_sphere',
            field=models.CharField(blank=True, help_text='Ej: +2.50, -1.25, N/A', max_length=10, null=True, verbose_name='OS Esfera'),
        ),
    ]
