# Generated by Django 3.2.25 on 2026-01-08 23:01

import apps.audit.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0025_alter_organization_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRetentionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ejecución')),
                ('logs_deleted', models.IntegerField(default=0, verbose_name='Logs eliminados')),
                ('oldest_date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Fecha más antigua eliminada')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='Duración (segundos)')),
                ('details', apps.audit.models.JSONFieldCompatible(default=dict, help_text='Detalles de la ejecución', verbose_name='Detalles')),
            ],
            options={
                'verbose_name': 'Registro de limpieza',
                'verbose_name_plural': 'Registros de limpieza',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión'), ('LOGIN_FAILED', 'Intento de login fallido'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('PRINT', 'Imprimir'), ('EMAIL', 'Enviar email'), ('SMS', 'Enviar SMS'), ('WHATSAPP', 'Enviar WhatsApp'), ('PAYMENT', 'Pago'), ('REFUND', 'Reembolso'), ('OTHER', 'Otra acción')], db_index=True, max_length=20, verbose_name='Acción')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID del objeto')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Representación del objeto')),
                ('changes', apps.audit.models.JSONFieldCompatible(default=dict, help_text='JSON con cambios antes/después', verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador y sistema operativo', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('metadata', apps.audit.models.JSONFieldCompatible(default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadatos')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la acción', verbose_name='Descripción')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Nombre del modelo (app.Model)', max_length=100, verbose_name='Modelo')),
                ('track_creates', models.BooleanField(default=True, verbose_name='Auditar creaciones')),
                ('track_updates', models.BooleanField(default=True, verbose_name='Auditar actualizaciones')),
                ('track_deletes', models.BooleanField(default=True, verbose_name='Auditar eliminaciones')),
                ('track_reads', models.BooleanField(default=False, help_text='Puede generar muchos registros', verbose_name='Auditar lecturas')),
                ('retention_days', models.IntegerField(default=365, help_text='Días para mantener los logs antes de eliminarlos', verbose_name='Días de retención')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('excluded_fields', apps.audit.models.JSONFieldCompatible(default=dict, help_text='Lista de campos que no se auditarán', verbose_name='Campos excluidos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('organization', models.ForeignKey(blank=True, help_text='Dejar vacío para configuración global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_configs', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración de auditoría',
                'verbose_name_plural': 'Configuraciones de auditoría',
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', '-created_at'], name='audit_audit_user_id_5f68a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='audit_audit_organiz_c1c99d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='audit_audit_ip_addr_ff6f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditconfig',
            index=models.Index(fields=['model_name', 'is_active'], name='audit_audit_model_n_eeab0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditconfig',
            unique_together={('model_name', 'organization')},
        ),
    ]
