# Generated by Django 3.2.25 on 2026-01-10 04:33

import apps.audit.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('error_type', models.CharField(help_text='ValueError, AttributeError, KeyError, etc.', max_length=200, verbose_name='Tipo de error')),
                ('error_message', models.TextField(verbose_name='Mensaje de error')),
                ('stack_trace', models.TextField(verbose_name='Stack trace completo')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('method', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE, etc.', max_length=10, verbose_name='Método HTTP')),
                ('request_data', apps.audit.models.JSONFieldCompatible(default=dict, help_text='GET params, POST data, etc.', verbose_name='Datos de petición')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('context', apps.audit.models.JSONFieldCompatible(default=dict, help_text='Variables locales, estado de la sesión, etc.', verbose_name='Contexto adicional')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto en')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('occurrence_count', models.IntegerField(default=1, verbose_name='Veces que ocurrió')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Primera vez visto')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Última vez visto')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Severidad')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='organizations.organization', verbose_name='Organización')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Error de sistema',
                'verbose_name_plural': 'Errores de sistema',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['error_type', 'is_resolved'], name='audit_error_error_t_230529_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['-timestamp'], name='audit_error_timesta_ef07a5_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_error_user_id_896f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['severity', 'is_resolved'], name='audit_error_severit_8cbc12_idx'),
        ),
    ]
