# Generated by Django 3.2.25 on 2026-01-09 00:21

import apps.workflows.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0025_alter_organization_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('initial_state', models.CharField(help_text='Estado inicial cuando se crea una instancia', max_length=100, verbose_name='Estado Inicial')),
                ('states', apps.workflows.models.JSONFieldCompatible(default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Lista de estados posibles: [{"key": "draft", "name": "Borrador", "color": "#ccc"}]', verbose_name='Estados')),
                ('final_states', apps.workflows.models.JSONFieldCompatible(default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Lista de estados finales (completados/cancelados)', verbose_name='Estados Finales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('auto_start', models.BooleanField(default=False, help_text='Iniciar workflow automáticamente al crear el objeto', verbose_name='Inicio Automático')),
                ('require_approval', models.BooleanField(default=False, help_text='Workflow requiere aprobaciones en transiciones', verbose_name='Requiere Aprobación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('content_type', models.ForeignKey(help_text='Tipo de objeto al que se aplica este workflow', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Definición de Workflow',
                'verbose_name_plural': 'Definiciones de Workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('from_state', models.CharField(help_text='Estado desde el cual se puede hacer la transición', max_length=100, verbose_name='Estado Origen')),
                ('to_state', models.CharField(help_text='Estado al que se transiciona', max_length=100, verbose_name='Estado Destino')),
                ('conditions', apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Condiciones que deben cumplirse para la transición', verbose_name='Condiciones')),
                ('required_permission', models.CharField(blank=True, help_text='Permiso necesario para ejecutar esta transición', max_length=255, verbose_name='Permiso Requerido')),
                ('require_approval', models.BooleanField(default=False, help_text='Esta transición requiere aprobación', verbose_name='Requiere Aprobación')),
                ('approval_roles', apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Roles que pueden aprobar esta transición', verbose_name='Roles Aprobadores')),
                ('order', models.IntegerField(default=0, help_text='Orden de presentación', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='organizations.organization', verbose_name='Organización')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowdefinition', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Transición de Workflow',
                'verbose_name_plural': 'Transiciones de Workflows',
                'ordering': ['workflow', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID Objeto')),
                ('current_state', models.CharField(db_index=True, max_length=100, verbose_name='Estado Actual')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('suspended', 'Suspendido'), ('error', 'Error')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('data', apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Datos adicionales del workflow', verbose_name='Datos')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='organizations.organization', verbose_name='Organización')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowdefinition', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Instancia de Workflow',
                'verbose_name_plural': 'Instancias de Workflows',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=100, verbose_name='Estado Anterior')),
                ('to_state', models.CharField(max_length=100, verbose_name='Estado Nuevo')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('metadata', apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Datos adicionales de la transición', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflows.workflowinstance', verbose_name='Instancia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='organizations.organization', verbose_name='Organización')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowtransition', verbose_name='Transición')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions_made', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Workflow',
                'verbose_name_plural': 'Historiales de Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado en')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido en')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approvals_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowinstance', verbose_name='Instancia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to='organizations.organization', verbose_name='Organización')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowtransition', verbose_name='Transición')),
            ],
            options={
                'verbose_name': 'Aprobación de Workflow',
                'verbose_name_plural': 'Aprobaciones de Workflows',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('state', models.CharField(blank=True, help_text='Estado que dispara esta acción (alternativa a transición)', max_length=100, verbose_name='Estado')),
                ('action_type', models.CharField(choices=[('send_notification', 'Enviar Notificación'), ('send_email', 'Enviar Email'), ('create_task', 'Crear Tarea'), ('update_field', 'Actualizar Campo'), ('call_webhook', 'Llamar Webhook'), ('execute_script', 'Ejecutar Script'), ('assign_user', 'Asignar Usuario')], max_length=50, verbose_name='Tipo de Acción')),
                ('trigger', models.CharField(choices=[('on_enter', 'Al Entrar al Estado'), ('on_exit', 'Al Salir del Estado'), ('on_transition', 'En la Transición')], default='on_transition', max_length=20, verbose_name='Disparador')),
                ('parameters', apps.workflows.models.JSONFieldCompatible(default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Parámetros específicos de la acción', verbose_name='Parámetros')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Ejecución')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='organizations.organization', verbose_name='Organización')),
                ('transition', models.ForeignKey(blank=True, help_text='Transición que dispara esta acción (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowtransition', verbose_name='Transición')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowdefinition', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Acción de Workflow',
                'verbose_name_plural': 'Acciones de Workflows',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['workflow', 'from_state'], name='workflows_w_workflo_002bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['organization', 'is_active'], name='workflows_w_organiz_68b72d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_f0a0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['organization', 'current_state'], name='workflows_w_organiz_bdcd70_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_w_content_9e540a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['started_by', 'status'], name='workflows_w_started_d1d69b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['instance', 'created_at'], name='workflows_w_instanc_8e9c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['organization', 'created_at'], name='workflows_w_organiz_639d65_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['user', 'created_at'], name='workflows_w_user_id_4e4b41_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['organization', 'is_active'], name='workflows_w_organiz_3a1ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['content_type', 'is_active'], name='workflows_w_content_4984ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['instance', 'status'], name='workflows_w_instanc_16132b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['approver', 'status'], name='workflows_w_approve_aec63c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowapproval',
            index=models.Index(fields=['organization', 'requested_at'], name='workflows_w_organiz_f1b882_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['workflow', 'is_active'], name='workflows_w_workflo_081354_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['transition', 'trigger'], name='workflows_w_transit_72417f_idx'),
        ),
    ]
