# Generated by Django 3.2.25 on 2026-01-13 17:37

import apps.workflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20260109_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaction',
            name='parameters',
            field=apps.workflows.models.JSONFieldCompatible(default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Parámetros específicos de la acción', verbose_name='Parámetros'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='final_states',
            field=apps.workflows.models.JSONFieldCompatible(default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Lista de estados finales (completados/cancelados)', verbose_name='Estados Finales'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='states',
            field=apps.workflows.models.JSONFieldCompatible(default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Lista de estados posibles: [{"key": "draft", "name": "Borrador", "color": "#ccc"}]', verbose_name='Estados'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='metadata',
            field=apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Datos adicionales de la transición', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='data',
            field=apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Datos adicionales del workflow', verbose_name='Datos'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='approval_roles',
            field=apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Roles que pueden aprobar esta transición', verbose_name='Roles Aprobadores'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='conditions',
            field=apps.workflows.models.JSONFieldCompatible(blank=True, default=apps.workflows.models.JSONFieldCompatible._get_default, help_text='Condiciones que deben cumplirse para la transición', verbose_name='Condiciones'),
        ),
    ]
