# Generated by Django 3.2.25 on 2026-01-08 23:29

import apps.reports.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0025_alter_organization_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('parameters', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Filtros y parámetros aplicados al generar', verbose_name='Parámetros')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Fecha desde')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Fecha hasta')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=20, verbose_name='Formato')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Archivo')),
                ('results', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Datos del reporte en formato JSON', verbose_name='Resultados')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total de registros')),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de generación (s)')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha en que se elimina automáticamente', null=True, verbose_name='Expira el')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('report_type', models.CharField(choices=[('sales', 'Ventas'), ('patients', 'Pacientes'), ('appointments', 'Citas'), ('inventory', 'Inventario'), ('financial', 'Financiero'), ('clinical', 'Clínico'), ('hr', 'Recursos Humanos'), ('analytics', 'Analytics'), ('custom', 'Personalizado')], db_index=True, max_length=50, verbose_name='Tipo de reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('config', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Configuración en formato JSON (filtros, campos, agrupaciones)', verbose_name='Configuración')),
                ('custom_query', models.TextField(blank=True, help_text='Query SQL para reportes avanzados', verbose_name='Query personalizado')),
                ('columns', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Lista de columnas a mostrar', verbose_name='Columnas')),
                ('default_filters', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Filtros que se aplican por defecto', verbose_name='Filtros por defecto')),
                ('grouping', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Campos por los que agrupar', verbose_name='Agrupaciones')),
                ('ordering', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Orden de los resultados', verbose_name='Ordenamiento')),
                ('is_system', models.BooleanField(default=False, verbose_name='Es del sistema')),
                ('is_public', models.BooleanField(default=False, help_text='Visible para todos los usuarios de la org', verbose_name='Es público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, help_text='Dejar vacío para plantilla global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Plantilla de reporte',
                'verbose_name_plural': 'Plantillas de reporte',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Frecuencia')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Lunes, 6=Domingo', null=True, verbose_name='Día de la semana')),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-31', null=True, verbose_name='Día del mes')),
                ('time', models.TimeField(default='09:00:00', verbose_name='Hora')),
                ('parameters', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Parámetros para la generación', verbose_name='Parámetros')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=20, verbose_name='Formato')),
                ('recipients', apps.reports.models.JSONFieldCompatible(default=dict, help_text='Lista de emails para enviar el reporte', verbose_name='Destinatarios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución')),
                ('last_run_status', models.CharField(blank=True, max_length=20, verbose_name='Estado última ejecución')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Próxima ejecución')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='organizations.organization', verbose_name='Organización')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reports.reporttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Reporte programado',
                'verbose_name_plural': 'Reportes programados',
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(blank=True, max_length=254, verbose_name='Email destinatario')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('can_download', models.BooleanField(default=True, verbose_name='Puede descargar')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Visto el')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.report', verbose_name='Reporte')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_shared', to=settings.AUTH_USER_MODEL, verbose_name='Compartido por')),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Compartido con')),
            ],
            options={
                'verbose_name': 'Compartir reporte',
                'verbose_name_plural': 'Reportes compartidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate', verbose_name='Plantilla'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['is_active', 'next_run_at'], name='reports_sch_is_acti_5f302e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['organization', 'is_active'], name='reports_sch_organiz_1e2f52_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type', 'is_active'], name='reports_rep_report__11a031_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'is_public'], name='reports_rep_organiz_d9694c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='reports_rep_organiz_9e3954_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', '-created_at'], name='reports_rep_generat_ef0442_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['expires_at'], name='reports_rep_expires_6eb760_idx'),
        ),
    ]
