# Generated by Django 5.2.8 on 2026-01-06 21:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('BASICO', 'Salario Básico'), ('AUXILIO_TRANSPORTE', 'Auxilio de Transporte'), ('HORAS_EXTRAS', 'Horas Extras'), ('RECARGO_NOCTURNO', 'Recargo Nocturno'), ('RECARGO_DOMINICAL', 'Recargo Dominical/Festivo'), ('COMISION', 'Comisión'), ('BONIFICACION', 'Bonificación'), ('PRIMA', 'Prima'), ('CESANTIAS', 'Cesantías'), ('INTERESES_CESANTIAS', 'Intereses Cesantías'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad'), ('LICENCIA', 'Licencia'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('aplica_seguridad_social', models.BooleanField(default=True, help_text='¿Aplica para base de seguridad social?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Concepto de Devengado',
                'verbose_name_plural': 'Conceptos de Devengados',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DeductionConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('SALUD', 'Salud (4%)'), ('PENSION', 'Pensión (4%)'), ('FONDO_SOLIDARIDAD', 'Fondo de Solidaridad Pensional'), ('RETENCION_FUENTE', 'Retención en la Fuente'), ('LIBRANZA', 'Libranza'), ('EMBARGO', 'Embargo Judicial'), ('PRESTAMO', 'Préstamo'), ('FONDO_EMPLEADOS', 'Fondo de Empleados'), ('OTRO', 'Otra Deducción')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('porcentaje_base', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje que se aplica automáticamente (ej: 4 para salud)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Concepto de Deducción',
                'verbose_name_plural': 'Conceptos de Deducciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2)),
                ('numero_documento', models.CharField(db_index=True, max_length=20, unique=True)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(default='CO', max_length=2)),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('FIJO', 'Término Fijo'), ('OBRA', 'Obra o Labor'), ('APRENDIZAJE', 'Aprendizaje'), ('PRESTACION', 'Prestación de Servicios')], default='INDEFINIDO', max_length=20)),
                ('subtipo_trabajador', models.CharField(choices=[('00', 'Dependiente'), ('01', 'Dependiente Pensionado'), ('02', 'Dependiente Pensionado Activo')], default='00', max_length=2)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=200)),
                ('salario_basico', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.IntegerField(default=30)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='payroll.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Entrada de Nómina',
                'verbose_name_plural': 'Entradas de Nómina',
                'ordering': ['periodo', 'empleado'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicPayrollDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('cufe', models.CharField(blank=True, help_text='Código Único de Factura Electrónica', max_length=255, null=True)),
                ('xml_content', models.TextField(blank=True, null=True)),
                ('xml_signed', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('FIRMADO', 'Firmado'), ('ENVIADO', 'Enviado a DIAN'), ('APROBADO', 'Aprobado por DIAN'), ('RECHAZADO', 'Rechazado por DIAN')], default='GENERADO', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('respuesta_dian', models.TextField(blank=True, null=True)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10, null=True)),
                ('mensaje_respuesta', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payroll/pdf/')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='payroll/xml/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_document', to='payroll.payrollentry')),
            ],
            options={
                'verbose_name': 'Documento Electrónico de Nómina',
                'verbose_name_plural': 'Documentos Electrónicos de Nómina',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje aplicado', max_digits=5, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.deductionconcept')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payrollentry')),
            ],
            options={
                'verbose_name': 'Deducción',
                'verbose_name_plural': 'Deducciones',
                'ordering': ['entrada', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.accrualconcept')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='payroll.payrollentry')),
            ],
            options={
                'verbose_name': 'Devengado',
                'verbose_name_plural': 'Devengados',
                'ordering': ['entrada', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_periodo', models.CharField(choices=[('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='MENSUAL', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADO', 'Calculado'), ('APROBADO', 'Aprobado'), ('ENVIADO_DIAN', 'Enviado a DIAN'), ('VALIDADO_DIAN', 'Validado por DIAN'), ('RECHAZADO_DIAN', 'Rechazado por DIAN'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=20)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod'),
        ),
        migrations.AddIndex(
            model_name='accrualconcept',
            index=models.Index(fields=['organization', 'activo'], name='payroll_acc_organiz_e8dd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='deductionconcept',
            index=models.Index(fields=['organization', 'activo'], name='payroll_ded_organiz_37b1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'activo'], name='payroll_emp_organiz_043488_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['numero_documento'], name='payroll_emp_numero__86579b_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicpayrolldocument',
            index=models.Index(fields=['organization', 'estado'], name='payroll_ele_organiz_3569c9_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicpayrolldocument',
            index=models.Index(fields=['consecutivo'], name='payroll_ele_consecu_3b58b8_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicpayrolldocument',
            index=models.Index(fields=['cufe'], name='payroll_ele_cufe_9b898e_idx'),
        ),
        migrations.AddIndex(
            model_name='deduction',
            index=models.Index(fields=['organization', 'entrada'], name='payroll_ded_organiz_4e397f_idx'),
        ),
        migrations.AddIndex(
            model_name='accrual',
            index=models.Index(fields=['organization', 'entrada'], name='payroll_acc_organiz_b92373_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['organization', 'estado'], name='payroll_pay_organiz_e0bf69_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='payroll_pay_fecha_i_940d09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('organization', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['organization', 'periodo'], name='payroll_pay_organiz_69f9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['empleado'], name='payroll_pay_emplead_bda50c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together={('periodo', 'empleado')},
        ),
    ]
