# Generated by Django 3.2.25 on 2026-01-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualconcept',
            name='aplica_prestaciones',
            field=models.BooleanField(default=True, help_text='¿Aplica para base de prestaciones sociales?'),
        ),
        migrations.AddField(
            model_name='deductionconcept',
            name='base_calculo',
            field=models.CharField(choices=[('SALARIO', 'Sobre Salario Base'), ('VALOR_FIJO', 'Valor Fijo'), ('DEVENGADO', 'Sobre Total Devengado')], default='SALARIO', help_text='Sobre qué base se calcula la deducción', max_length=20),
        ),
        migrations.AddField(
            model_name='deductionconcept',
            name='es_obligatoria',
            field=models.BooleanField(default=False, help_text='Deducción de ley (salud, pensión, etc.)'),
        ),
        migrations.AlterField(
            model_name='accrualconcept',
            name='tipo',
            field=models.CharField(choices=[('SALARIO', 'Salario Básico'), ('HORAS_EXTRAS', 'Horas Extras'), ('RECARGO', 'Recargo Nocturno/Festivo'), ('AUXILIO', 'Auxilio'), ('COMISION', 'Comisión'), ('BONIFICACION', 'Bonificación'), ('PRESTACION', 'Prestación Social'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad'), ('LICENCIA', 'Licencia'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='deductionconcept',
            name='tipo',
            field=models.CharField(choices=[('SALUD', 'Salud (4%)'), ('PENSION', 'Pensión (4%)'), ('FSP', 'Fondo de Solidaridad Pensional'), ('RETENCION', 'Retención en la Fuente'), ('PRESTAMO', 'Préstamo'), ('EMBARGO', 'Embargo Judicial'), ('COOPERATIVA', 'Cooperativa'), ('SINDICATO', 'Sindicato'), ('AHORRO', 'Ahorro Programado'), ('LIBRANZA', 'Libranza'), ('FONDO', 'Fondo de Empleados'), ('OTRO', 'Otra Deducción')], max_length=30),
        ),
    ]
