# Generated by Django 3.2.25 on 2026-01-06 23:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_auto_20260106_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriodWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador - Generado automáticamente'), ('EN_REVISION', 'En Revisión - Esperando aprobación'), ('APROBADO', 'Aprobado - Listo para procesar'), ('PROCESADO', 'Procesado - Nómina ejecutada'), ('RECHAZADO', 'Rechazado - Requiere correcciones'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('fecha_borrador', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('notas_revision', models.TextField(blank=True)),
                ('notas_aprobacion', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('validaciones_pasadas', models.TextField(blank=True, default='')),
                ('errores_validacion', models.TextField(blank=True, default='')),
                ('warnings', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrollperiodworkflow_set', to='organizations.organization', verbose_name='Organización')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='payroll.payrollperiod')),
                ('usuario_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_procesados', to=settings.AUTH_USER_MODEL)),
                ('usuario_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow de Período',
                'verbose_name_plural': 'Workflows de Períodos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BORRADOR_GENERADO', 'Borrador Generado'), ('REVISION_PENDIENTE', 'Revisión Pendiente'), ('APROBACION_REQUERIDA', 'Aprobación Requerida'), ('NOMINA_APROBADA', 'Nómina Aprobada'), ('NOMINA_PROCESADA', 'Nómina Procesada'), ('NOMINA_RECHAZADA', 'Nómina Rechazada'), ('ERROR_CALCULO', 'Error en Cálculo'), ('WARNING', 'Advertencia')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('requiere_accion', models.BooleanField(default=False)),
                ('url_accion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrollnotification_set', to='organizations.organization', verbose_name='Organización')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='payroll.payrollperiod')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='notificaciones_nomina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calculo', models.CharField(choices=[('INICIAL', 'Cálculo Inicial'), ('RECALCULO', 'Recálculo'), ('AUTOMATICO', 'Generación Automática'), ('MANUAL', 'Ajuste Manual')], max_length=20)),
                ('empleados_procesados', models.IntegerField(default=0)),
                ('empleados_con_errores', models.IntegerField(default=0)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deducido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('detalles', models.TextField(blank=True, default='')),
                ('errores', models.TextField(blank=True, default='')),
                ('tiempo_inicio', models.DateTimeField(auto_now_add=True)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrollcalculationlog_set', to='organizations.organization', verbose_name='Organización')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_calculo', to='payroll.payrollperiod')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Cálculo',
                'verbose_name_plural': 'Logs de Cálculos',
                'ordering': ['-tiempo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_pago_mensual', models.IntegerField(default=30, help_text='Día del mes para pago de nómina mensual (1-31)', validators=[django.core.validators.MinValueValidator(1)])),
                ('dia_pago_quincenal_1', models.IntegerField(default=15, help_text='Primer día de pago quincenal', validators=[django.core.validators.MinValueValidator(1)])),
                ('dia_pago_quincenal_2', models.IntegerField(default=30, help_text='Segundo día de pago quincenal', validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_generar_borradores', models.BooleanField(default=True, help_text='Generar automáticamente borradores de nómina')),
                ('dias_anticipacion_borrador', models.IntegerField(default=5, help_text='Días antes de la fecha de pago para generar borrador')),
                ('enviar_notificacion_borrador', models.BooleanField(default=True)),
                ('enviar_notificacion_aprobacion', models.BooleanField(default=True)),
                ('enviar_notificacion_procesado', models.BooleanField(default=True)),
                ('validar_salario_minimo', models.BooleanField(default=True)),
                ('validar_seguridad_social', models.BooleanField(default=True)),
                ('validar_prestaciones', models.BooleanField(default=True)),
                ('calcular_horas_extras', models.BooleanField(default=True)),
                ('calcular_auxilio_transporte', models.BooleanField(default=True)),
                ('calcular_prestaciones_sociales', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrollautomationconfig_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración de Automatización',
                'verbose_name_plural': 'Configuraciones de Automatización',
            },
        ),
        migrations.CreateModel(
            name='EmployeePeriodAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incluido', models.BooleanField(default=True, help_text='Si está incluido en este período de nómina')),
                ('motivo_exclusion', models.TextField(blank=True)),
                ('salario_periodo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dias_trabajados', models.IntegerField(default=30, help_text='Días trabajados en este período', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_devengado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deducido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calculado_automaticamente', models.BooleanField(default=False)),
                ('fecha_calculo', models.DateTimeField(blank=True, null=True)),
                ('requiere_recalculo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_periodo', to='payroll.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeperiodassignment_set', to='organizations.organization', verbose_name='Organización')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Asignación de Empleado a Período',
                'verbose_name_plural': 'Asignaciones de Empleados a Períodos',
                'ordering': ['employee__primer_apellido', 'employee__primer_nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiodworkflow',
            index=models.Index(fields=['organization', 'estado'], name='payroll_pay_organiz_352711_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollnotification',
            index=models.Index(fields=['organization', 'leida'], name='payroll_pay_organiz_0d2d14_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollnotification',
            index=models.Index(fields=['tipo'], name='payroll_pay_tipo_019263_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcalculationlog',
            index=models.Index(fields=['organization', 'period'], name='payroll_pay_organiz_410ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcalculationlog',
            index=models.Index(fields=['tipo_calculo'], name='payroll_pay_tipo_ca_9e0c48_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeperiodassignment',
            index=models.Index(fields=['organization', 'period', 'incluido'], name='payroll_emp_organiz_8660d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeperiodassignment',
            unique_together={('period', 'employee')},
        ),
    ]
