# Generated by Django 3.2.25 on 2026-01-06 23:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20260106_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='auxilio_transporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('162000'), help_text='Auxilio de transporte legal vigente', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_fsp_16_a_17',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.20'), help_text='Porcentaje FSP para salarios entre 16 y 17 SMLV (por defecto 1.2%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_fsp_17_a_18',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.40'), help_text='Porcentaje FSP para salarios entre 17 y 18 SMLV (por defecto 1.4%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_fsp_18_a_19',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.60'), help_text='Porcentaje FSP para salarios entre 18 y 19 SMLV (por defecto 1.6%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_fsp_19_a_20',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.80'), help_text='Porcentaje FSP para salarios entre 19 y 20 SMLV (por defecto 1.8%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_fsp_4_a_16',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Porcentaje FSP para salarios entre 4 y 16 SMLV (por defecto 1%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_fsp_mayor_20',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Porcentaje FSP para salarios mayores a 20 SMLV (por defecto 2%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_pension',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Porcentaje de pensión que aporta el empleado (por defecto 4%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='porcentaje_salud',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Porcentaje de salud que aporta el empleado (por defecto 4%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payrollautomationconfig',
            name='salario_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('1300000'), help_text='Salario mínimo legal vigente', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
