# Generated by Django 5.2.8 on 2026-01-07 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_employeeloan_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Contador o propietario que aprobó la nómina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='rol_aprobador',
            field=models.CharField(blank=True, choices=[('PROPIETARIO', 'Propietario'), ('CONTADOR', 'Contador'), ('ADMIN', 'Administrador')], help_text='Rol del usuario que aprobó', max_length=20, null=True),
        ),
    ]
