# Generated by Django 3.2.25 on 2026-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrollperiod_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrualconcept',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deductionconcept',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='accrualconcept',
            constraint=models.UniqueConstraint(fields=('organization', 'codigo'), name='unique_accrual_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='deductionconcept',
            constraint=models.UniqueConstraint(fields=('organization', 'codigo'), name='unique_deduction_code_per_org'),
        ),
    ]
