# Generated by Django 3.2.25 on 2025-11-29 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Formato válido: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de celular')),
                ('appointment_date', models.DateField(verbose_name='Fecha de cita')),
                ('appointment_time', models.TimeField(verbose_name='Hora de cita')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del administrador', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text='Activa/desactiva el sistema de agendamiento', verbose_name='Sistema abierto')),
                ('slot_duration', models.IntegerField(default=30, verbose_name='Duración de cita (minutos)')),
                ('max_daily_appointments', models.IntegerField(default=20, verbose_name='Máximo de citas diarias')),
                ('advance_booking_days', models.IntegerField(default=30, verbose_name='Días de anticipación para agendar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Citas',
                'verbose_name_plural': 'Configuración de Citas',
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha bloqueada')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fecha Bloqueada',
                'verbose_name_plural': 'Fechas Bloqueadas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('manually_blocked', models.BooleanField(default=False, verbose_name='Bloqueado manualmente')),
                ('blocked_reason', models.CharField(blank=True, max_length=200, verbose_name='Razón de bloqueo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slot de Tiempo',
                'verbose_name_plural': 'Slots de Tiempo',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('day_of_week', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'is_available'], name='appointment_date_49e0fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'time')},
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.patient', verbose_name='Paciente'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_fb412a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['phone_number'], name='appointment_phone_n_c8dbe7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_date', 'appointment_time')},
        ),
    ]
