# Generated by Django 3.2.25 on 2025-12-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('appointments', '0002_specificdateschedule'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_appoint_fb412a_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_phone_n_c8dbe7_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeslot',
            name='appointment_date_49e0fa_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='appointmentconfiguration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentconfiguration_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockeddate_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='specificdateschedule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificdateschedule_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workinghours_set', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='date',
            field=models.DateField(verbose_name='Fecha bloqueada'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('organization', 'appointment_date', 'appointment_time')},
        ),
        migrations.AlterUniqueTogether(
            name='appointmentconfiguration',
            unique_together={('organization',)},
        ),
        migrations.AlterUniqueTogether(
            name='blockeddate',
            unique_together={('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='specificdateschedule',
            unique_together={('organization', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('organization', 'date', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('organization', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'appointment_date', 'status'], name='appointment_organiz_b408e3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'phone_number'], name='appointment_organiz_e1c224_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['organization', 'date', 'is_available'], name='appointment_organiz_53ce1b_idx'),
        ),
    ]
