# Generated by Django 3.2.25 on 2025-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20251201_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para notificaciones (opcional)', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
