# Generated by Django 3.2.25 on 2025-12-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_neighborhood'),
        ('appointments', '0004_appointment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_enabled', models.BooleanField(default=False, verbose_name='Habilitar WhatsApp (Twilio)')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=200, verbose_name='Twilio Account SID')),
                ('twilio_auth_token', models.CharField(blank=True, max_length=200, verbose_name='Twilio Auth Token')),
                ('twilio_whatsapp_from', models.CharField(default='whatsapp:+14155238886', max_length=50, verbose_name='Número WhatsApp (Twilio)')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Habilitar Email')),
                ('email_from', models.EmailField(blank=True, help_text='Deja vacío para usar el email por defecto del sistema', max_length=254, verbose_name='Email remitente')),
                ('local_whatsapp_enabled', models.BooleanField(default=False, verbose_name='Habilitar WhatsApp Local (Baileys)')),
                ('local_whatsapp_url', models.URLField(default='http://localhost:3000', verbose_name='URL del bot local')),
                ('send_confirmation', models.BooleanField(default=True, verbose_name='Enviar confirmación al agendar')),
                ('send_reminder', models.BooleanField(default=True, verbose_name='Enviar recordatorio (1 día antes)')),
                ('send_cancellation', models.BooleanField(default=True, verbose_name='Enviar notificación de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsettings_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'unique_together': {('organization',)},
            },
        ),
    ]
