# Generated by Django 3.2.25 on 2025-12-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_alter_appointment_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificdateschedule',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='specificdateschedule',
            name='slot_duration',
            field=models.IntegerField(default=30, verbose_name='Duración de cita (minutos)'),
        ),
    ]
