# Generated by Django 3.2.25 on 2025-12-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20251211_1519'),
        ('appointments', '0007_auto_20251211_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Notificación push enviada')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de notificación')),
                ('created_from_landing', models.BooleanField(default=False, verbose_name='Creada desde landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_notification', to='appointments.appointment', verbose_name='Cita')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentnotification_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Notificación Push de Cita',
                'verbose_name_plural': 'Notificaciones Push de Citas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentnotification',
            index=models.Index(fields=['organization', 'is_notified', 'created_from_landing'], name='appointment_organiz_c2eb25_idx'),
        ),
    ]
