# Generated by Django 5.2.8 on 2025-12-13 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_doctor_and_more'),
        ('organizations', '0010_auto_20251211_1519'),
        ('patients', '0017_fix_clinical_history_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='companion_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del acompañante'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='companion_phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Teléfono del acompañante'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='companion_relationship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relación con el paciente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='has_companion',
            field=models.BooleanField(default=False, verbose_name='Viene con acompañante'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('organization', 'appointment_date', 'appointment_time'), name='unique_active_appointment_slot'),
        ),
    ]
