# Generated by Django 3.2.25 on 2025-12-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_companion_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('organization', 'appointment_date', 'appointment_time'), name='unique_active_appointment_slot'),
        ),
    ]
