# Generated by Django 5.2.8 on 2025-12-26 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointment_unique_active_appointment_slot'),
        ('patients', '0027_change_doctor_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specificdateschedule',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_schedules', to='patients.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='specificdateschedule',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Doctor (User - DEPRECATED)'),
        ),
    ]
