# Generated by Django 3.2.25 on 2026-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_add_doctor_profile_to_specific_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='twilio_auth_token',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='twilio_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='twilio_whatsapp_from',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Usa la cuenta Twilio configurada en el sistema', verbose_name='Habilitar notificaciones por WhatsApp'),
        ),
    ]
