# Generated by Django 3.2.25 on 2026-01-08 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        ('appointments', '0016_whatsapp_usage_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='whatsapp_enabled',
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('message_type', models.CharField(choices=[('appointment_confirmation', 'Confirmación de Cita'), ('appointment_reminder', 'Recordatorio de Cita'), ('appointment_cancelled', 'Cita Cancelada'), ('appointment_rescheduled', 'Cita Reagendada'), ('test_message', 'Mensaje de Prueba')], max_length=50, verbose_name='Tipo de mensaje')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_notifications', to='appointments.appointment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsappmessagelog_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['organization', 'sent_at'], name='appointment_organiz_eadd5f_idx'),
        ),
    ]
