# Generated by Django 3.2.25 on 2025-12-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Organización')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Color primario en hexadecimal', max_length=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('professional', 'Profesional'), ('enterprise', 'Empresarial')], default='free', max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Anual')),
                ('max_users', models.IntegerField(default=1, verbose_name='Máximo de Usuarios')),
                ('max_appointments_month', models.IntegerField(default=50, verbose_name='Máximo de Citas/Mes')),
                ('max_patients', models.IntegerField(default=100, verbose_name='Máximo de Pacientes')),
                ('max_storage_mb', models.IntegerField(default=100, verbose_name='Almacenamiento (MB)')),
                ('whatsapp_integration', models.BooleanField(default=False, verbose_name='Integración WhatsApp')),
                ('custom_branding', models.BooleanField(default=False, verbose_name='Marca Personalizada')),
                ('api_access', models.BooleanField(default=False, verbose_name='Acceso API')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Soporte Prioritario')),
                ('analytics', models.BooleanField(default=False, verbose_name='Análisis Avanzado')),
                ('multi_location', models.BooleanField(default=False, verbose_name='Múltiples Ubicaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación Automática')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('staff', 'Personal'), ('viewer', 'Visualizador')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Organización',
                'verbose_name_plural': 'Miembros de Organización',
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
