# Generated by Django 3.2.25 on 2025-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Nombre legal registrado de la empresa', max_length=300, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=200, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Secundario'),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado/Provincia'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Número de identificación fiscal', max_length=50, verbose_name='RUC/NIT/RFC'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
    ]
