# Generated by Django 3.2.25 on 2025-12-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20251202_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax_id_type',
            field=models.CharField(blank=True, choices=[('RUC', 'RUC - Registro Único de Contribuyentes'), ('NIT', 'NIT - Número de Identificación Tributaria'), ('RFC', 'RFC - Registro Federal de Contribuyentes'), ('CUIT', 'CUIT - Clave Única de Identificación Tributaria'), ('RUT', 'RUT - Rol Único Tributario'), ('OTHER', 'Otro')], max_length=10, verbose_name='Tipo de Documento Fiscal'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Número de identificación fiscal', max_length=50, verbose_name='Número Fiscal'),
        ),
    ]
