# Generated by Django 3.2.25 on 2025-12-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20251202_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio'),
        ),
    ]
