# Generated by Django 3.2.25 on 2025-12-04 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_bg_color', models.CharField(default='#ffffff', help_text='Color en formato hexadecimal (ej: #ffffff)', max_length=7, verbose_name='Color de fondo del Navbar')),
                ('navbar_text_color', models.CharField(default='#1f2937', help_text='Color en formato hexadecimal (ej: #1f2937)', max_length=7, verbose_name='Color del texto del Navbar')),
                ('navbar_hover_color', models.CharField(default='#2563eb', help_text='Color en formato hexadecimal (ej: #2563eb)', max_length=7, verbose_name='Color hover del Navbar')),
                ('hero_image', models.ImageField(blank=True, help_text='Recomendado: 1920x1080px', null=True, upload_to='landing/hero/', verbose_name='Imagen Principal (Hero)')),
                ('service_image_1', models.ImageField(blank=True, help_text='Recomendado: 612x612px', null=True, upload_to='landing/services/', verbose_name='Imagen Servicio 1 (Examen Visual)')),
                ('service_image_2', models.ImageField(blank=True, help_text='Recomendado: 612x612px', null=True, upload_to='landing/services/', verbose_name='Imagen Servicio 2 (Monturas)')),
                ('service_image_3', models.ImageField(blank=True, help_text='Recomendado: 612x612px', null=True, upload_to='landing/services/', verbose_name='Imagen Servicio 3 (Lentes de Contacto)')),
                ('service_image_4', models.ImageField(blank=True, help_text='Recomendado: 612x612px', null=True, upload_to='landing/services/', verbose_name='Imagen Servicio 4 (Lentes de Sol)')),
                ('hero_title', models.CharField(blank=True, default='Cuida tu Salud Visual', max_length=200, verbose_name='Título Principal')),
                ('hero_subtitle', models.TextField(blank=True, default='Tecnología de última generación y atención personalizada para el cuidado de tus ojos.', verbose_name='Subtítulo Principal')),
                ('primary_button_color', models.CharField(default='#2563eb', help_text='Color en formato hexadecimal (ej: #2563eb)', max_length=7, verbose_name='Color Botón Primario')),
                ('secondary_button_color', models.CharField(default='#ffffff', help_text='Color en formato hexadecimal (ej: #ffffff)', max_length=7, verbose_name='Color Botón Secundario')),
                ('footer_bg_color', models.CharField(default='#111827', help_text='Color en formato hexadecimal (ej: #111827)', max_length=7, verbose_name='Color de fondo del Footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_config', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración de Landing Page',
                'verbose_name_plural': 'Configuraciones de Landing Page',
            },
        ),
    ]
