# Generated by Django 3.2.25 on 2025-12-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_landingpageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='contact_subtitle',
            field=models.TextField(blank=True, default='Estamos aquí para ayudarte. Contáctanos por cualquiera de nuestros canales.', verbose_name='Subtítulo Contacto'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='contact_title',
            field=models.CharField(blank=True, default='¿Tienes Preguntas?', max_length=200, verbose_name='Título Contacto'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_subtitle_color',
            field=models.CharField(default='#bfdbfe', help_text='Color en formato hexadecimal (ej: #bfdbfe)', max_length=7, verbose_name='Color del Subtítulo Principal'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_title_color',
            field=models.CharField(default='#ffffff', help_text='Color en formato hexadecimal (ej: #ffffff)', max_length=7, verbose_name='Color del Título Principal'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_1_description',
            field=models.TextField(blank=True, default='Evaluación exhaustiva de tu salud visual con equipos de última generación.', verbose_name='Descripción Servicio 1'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_1_title',
            field=models.CharField(blank=True, default='Examen Visual Completo', max_length=100, verbose_name='Título Servicio 1'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_2_description',
            field=models.TextField(blank=True, default='Amplio catálogo de monturas y lentes de las mejores marcas.', verbose_name='Descripción Servicio 2'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_2_title',
            field=models.CharField(blank=True, default='Monturas y Lentes', max_length=100, verbose_name='Título Servicio 2'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_3_description',
            field=models.TextField(blank=True, default='Adaptación profesional y variedad de lentes de contacto.', verbose_name='Descripción Servicio 3'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_3_title',
            field=models.CharField(blank=True, default='Lentes de Contacto', max_length=100, verbose_name='Título Servicio 3'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_4_description',
            field=models.TextField(blank=True, default='Protección UV total con estilo y calidad garantizada.', verbose_name='Descripción Servicio 4'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='service_4_title',
            field=models.CharField(blank=True, default='Lentes de Sol', max_length=100, verbose_name='Título Servicio 4'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='services_subtitle',
            field=models.CharField(blank=True, default='Cuidado integral para tu salud visual', max_length=200, verbose_name='Subtítulo Servicios'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='services_title',
            field=models.CharField(blank=True, default='Nuestros Servicios', max_length=200, verbose_name='Título Servicios'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='why_choose_subtitle',
            field=models.CharField(blank=True, default='La mejor atención para tus ojos', max_length=200, verbose_name='Subtítulo "Por qué elegirnos"'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='why_choose_title',
            field=models.CharField(blank=True, default='¿Por qué elegirnos?', max_length=200, verbose_name='Título "Por qué elegirnos"'),
        ),
    ]
