# Generated by Django 3.2.25 on 2025-12-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20251203_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='navbar_style',
            field=models.CharField(choices=[('classic', 'Clásico - Navbar blanco con sombra'), ('modern', 'Moderno - Navbar con gradiente y transparencia'), ('minimal', 'Minimalista - Navbar transparente con línea inferior'), ('bold', 'Bold - Navbar oscuro con contraste alto')], default='classic', help_text='Selecciona el diseño del navbar', max_length=20, verbose_name='Estilo del Navbar'),
        ),
    ]
