# Generated by Django 3.2.25 on 2025-12-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_landingpageconfig_navbar_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='animation_speed',
            field=models.CharField(choices=[('none', 'Sin animaciones'), ('slow', 'Lentas - Suaves y sutiles'), ('normal', 'Normales - Balance perfecto'), ('fast', 'Rápidas - Dinámicas y enérgicas')], default='normal', help_text='Controla las animaciones del sitio', max_length=20, verbose_name='Velocidad de animaciones'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='button_border_radius',
            field=models.IntegerField(default=8, help_text='En píxeles (0 = cuadrado, 999 = circular)', verbose_name='Radio de borde botones'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='button_shadow',
            field=models.BooleanField(default=True, help_text='Agrega sombra a los botones', verbose_name='Sombra en botones'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card_border_radius',
            field=models.IntegerField(default=12, help_text='En píxeles para tarjetas de servicios', verbose_name='Radio de borde tarjetas'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card_shadow_intensity',
            field=models.CharField(choices=[('none', 'Sin sombra'), ('sm', 'Suave'), ('md', 'Media'), ('lg', 'Fuerte'), ('xl', 'Extra fuerte')], default='md', help_text='Sombra de tarjetas y elementos', max_length=20, verbose_name='Intensidad de sombra'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='cta_badge_color',
            field=models.CharField(default='#10b981', help_text='Color del badge en hexadecimal', max_length=7, verbose_name='Color badge CTA'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='cta_badge_text',
            field=models.CharField(blank=True, help_text='Pequeño badge sobre título (ej: "Nuevo", "Popular")', max_length=50, verbose_name='Texto badge CTA'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='enable_hover_effects',
            field=models.BooleanField(default=True, help_text='Efectos al pasar el mouse', verbose_name='Efectos Hover'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='enable_parallax',
            field=models.BooleanField(default=False, help_text='Efecto de profundidad en scroll', verbose_name='Efecto Parallax'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter - Moderna y limpia'), ('roboto', 'Roboto - Profesional y versátil'), ('poppins', 'Poppins - Redondeada y amigable'), ('playfair', 'Playfair Display - Elegante y serif'), ('montserrat', 'Montserrat - Bold y geométrica'), ('lato', 'Lato - Clásica y legible')], default='inter', help_text='Tipografía principal del sitio', max_length=20, verbose_name='Familia de fuente'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='heading_font_size',
            field=models.IntegerField(default=48, help_text='Tamaño en píxeles', verbose_name='Tamaño título principal'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_bg_gradient_end',
            field=models.CharField(default='#8b5cf6', help_text='Color final del gradiente', max_length=7, verbose_name='Color fin degradado'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_bg_gradient_start',
            field=models.CharField(default='#3b82f6', help_text='Color inicial del gradiente', max_length=7, verbose_name='Color inicio degradado'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_overlay_opacity',
            field=models.IntegerField(default=50, help_text='0-100, aplica a imagen de fondo', verbose_name='Opacidad del overlay'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_style',
            field=models.CharField(choices=[('gradient', 'Gradiente - Fondo con degradado de colores'), ('image', 'Imagen - Imagen de fondo con overlay'), ('split', 'Split - Contenido dividido 50/50'), ('centered', 'Centrado - Contenido al centro con imagen de fondo'), ('video', 'Video - Fondo de video (próximamente)')], default='gradient', help_text='Diseño de la sección principal', max_length=20, verbose_name='Estilo del Hero'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='section_spacing',
            field=models.CharField(choices=[('compact', 'Compacto - Espacios pequeños'), ('normal', 'Normal - Balance estándar'), ('spacious', 'Espacioso - Espacios amplios')], default='normal', help_text='Espaciado vertical entre secciones', max_length=20, verbose_name='Espaciado de secciones'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='services_bg_color',
            field=models.CharField(default='#f9fafb', help_text='Color en formato hexadecimal', max_length=7, verbose_name='Color de fondo Servicios'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='services_layout',
            field=models.CharField(choices=[('grid', 'Grid - Tarjetas en cuadrícula'), ('carousel', 'Carrusel - Deslizable horizontal'), ('list', 'Lista - Vista vertical detallada'), ('masonry', 'Masonry - Diseño tipo Pinterest')], default='grid', help_text='Diseño de la sección de servicios', max_length=20, verbose_name='Layout de Servicios'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='show_scroll_indicator',
            field=models.BooleanField(default=True, help_text='Flecha animada en hero section', verbose_name='Indicador de scroll'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='show_stats',
            field=models.BooleanField(default=False, help_text='Números destacados (años, clientes, etc)', verbose_name='Mostrar estadísticas'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='show_testimonials',
            field=models.BooleanField(default=False, help_text='Sección de testimonios de clientes', verbose_name='Mostrar testimonios'),
        ),
    ]
