# Generated by Django 3.2.25 on 2025-12-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20251203_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa. Recomendado: 200x60px, fondo transparente PNG', null=True, upload_to='landing/logos/', verbose_name='Logo'),
        ),
    ]
