# Generated by Django 3.2.25 on 2025-12-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_landingpageconfig_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identificador único (ej: whatsapp_integration)', unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre visible del módulo', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('integration', 'Integración'), ('analytics', 'Análisis'), ('customization', 'Personalización'), ('communication', 'Comunicación'), ('medical', 'Médico'), ('sales', 'Ventas'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría')),
                ('icon', models.CharField(blank=True, help_text='ej: fa-whatsapp', max_length=50, verbose_name='Ícono FontAwesome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo/Característica',
                'verbose_name_plural': 'Módulos/Características',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='organizations.PlanFeature', verbose_name='Módulos/Características'),
        ),
    ]
