# Generated by Django 3.2.25 on 2025-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20251211_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_electronic_invoicing',
            field=models.BooleanField(default=False, help_text='¿Este plan incluye facturación electrónica DIAN?', verbose_name='Permite Facturación Electrónica'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_invoices_month',
            field=models.IntegerField(default=0, help_text='0 = Ilimitado (solo para plan empresarial full), N = cantidad específica', verbose_name='Máximo Facturas/Mes'),
        ),
    ]
