# Generated by Django 3.2.25 on 2025-12-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20251215_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_organizations',
            field=models.IntegerField(default=1, verbose_name='Máximo de Organizaciones'),
        ),
    ]
