# Generated by Django 3.2.25 on 2025-12-26 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_subscriptionplan_max_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='can_purchase_separately',
            field=models.BooleanField(default=False, help_text='¿Se puede comprar este módulo sin cambiar de plan?', verbose_name='Compra Individual'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio si se compra individualmente (0 = no disponible para compra individual)', max_digits=10, verbose_name='Precio Mensual'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('professional', 'Profesional'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoicePackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(50, '50 facturas'), (100, '100 facturas'), (200, '200 facturas'), (500, '500 facturas'), (1000, '1000 facturas')], verbose_name='Cantidad de Facturas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de Pago')),
                ('used_invoices', models.IntegerField(default=0, verbose_name='Facturas Usadas')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Opcional: fecha de vencimiento del paquete', null=True, verbose_name='Fecha de Expiración')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_purchases', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Compra de Paquete de Facturas',
                'verbose_name_plural': 'Compras de Paquetes de Facturas',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='AddonPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('lifetime', 'Vitalicio')], default='monthly', max_length=20, verbose_name='Ciclo de Facturación')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de Pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación Automática')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.planfeature', verbose_name='Módulo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_purchases', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Compra de Módulo Adicional',
                'verbose_name_plural': 'Compras de Módulos Adicionales',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('granted_by_plan', models.BooleanField(default=True, help_text='True si viene del plan, False si fue comprado por separado', verbose_name='Incluido en Plan')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to='organizations.planfeature', verbose_name='Módulo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_features', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Módulo de Organización',
                'verbose_name_plural': 'Módulos de Organizaciones',
                'ordering': ['organization', 'feature__category', 'feature__name'],
                'unique_together': {('organization', 'feature')},
            },
        ),
    ]
