# Generated by Django 3.2.25 on 2025-12-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_cascade_delete_on_user_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageconfig',
            name='navbar_style',
            field=models.CharField(choices=[('classic', 'Clásico - Navbar blanco con sombra'), ('modern', 'Moderno - Navbar con gradiente y transparencia'), ('minimal', 'Minimalista - Navbar transparente con línea inferior'), ('bold', 'Bold - Navbar oscuro con contraste alto'), ('glass', 'Glass - Efecto cristal difuminado (moderno)'), ('floating', 'Flotante - Navbar elevado con sombras suaves'), ('gradient_modern', 'Gradiente Moderno - Colores vibrantes'), ('sidebar', 'Sidebar - Navegación lateral (responsive)')], default='classic', help_text='Selecciona el diseño del navbar', max_length=20, verbose_name='Estilo del Navbar'),
        ),
    ]
