# Generated by Django 5.2.8 on 2025-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_add_new_navbar_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='logo_size',
            field=models.CharField(choices=[('small', 'Pequeño - 8 (32px)'), ('medium', 'Mediano - 10 (40px)'), ('large', 'Grande - 12 (48px)'), ('xlarge', 'Extra Grande - 16 (64px)'), ('xxlarge', 'Muy Grande - 20 (80px)')], default='medium', help_text='Selecciona el tamaño del logo en el navbar', max_length=10, verbose_name='Tamaño del Logo'),
        ),
    ]
