# Generated by Django 5.2.8 on 2025-12-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_add_logo_size_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_image_fit',
            field=models.CharField(choices=[('cover', 'Cubrir - Llena todo el espacio (puede recortar)'), ('contain', 'Contener - Muestra la imagen completa (sin recortar)'), ('fill', 'Rellenar - Estira la imagen para llenar el espacio'), ('none', 'Original - Tamaño original de la imagen')], default='contain', help_text='Cómo se ajusta la imagen de fondo en la sección principal', max_length=10, verbose_name='Ajuste de Imagen Hero'),
        ),
    ]
