# Generated by Django 5.2.8 on 2025-12-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_landingpageconfig_hero_image_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_image_position_x',
            field=models.IntegerField(default=50, help_text='0-100, posición horizontal de la imagen (%)', verbose_name='Posición Horizontal'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_image_position_y',
            field=models.IntegerField(default=50, help_text='0-100, posición vertical de la imagen (%)', verbose_name='Posición Vertical'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='hero_image_scale',
            field=models.IntegerField(default=100, help_text='50-200, tamaño de la imagen (%)', verbose_name='Escala de Imagen'),
        ),
    ]
