# Generated by Django 3.2.25 on 2025-12-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_landingpageconfig_hero_image_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageconfig',
            name='hero_image_fit',
            field=models.CharField(choices=[('cover', 'Cubrir - Llena todo el espacio (puede recortar)'), ('contain', 'Contener - Muestra la imagen completa (sin recortar)'), ('fill', 'Rellenar - Estira la imagen para llenar el espacio'), ('none', 'Original - Tamaño original de la imagen')], default='cover', help_text='Cómo se ajusta la imagen de fondo en la sección principal', max_length=10, verbose_name='Ajuste de Imagen Hero'),
        ),
    ]
