# Generated by Django 5.1.3 on 2025-12-27 manually created

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_change_hero_image_fit_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='schedule_weekday_start',
            field=models.CharField(default='10:00 AM', help_text='Formato: 10:00 AM', max_length=10, verbose_name='Hora de Inicio (Lunes-Viernes)'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='schedule_weekday_end',
            field=models.CharField(default='7:00 PM', help_text='Formato: 7:00 PM', max_length=10, verbose_name='Hora de Fin (Lunes-Viernes)'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='schedule_saturday_start',
            field=models.CharField(default='10:00 AM', help_text='Formato: 10:00 AM', max_length=10, verbose_name='Hora de Inicio (Sábado)'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='schedule_saturday_end',
            field=models.CharField(default='2:00 PM', help_text='Formato: 2:00 PM', max_length=10, verbose_name='Hora de Fin (Sábado)'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='schedule_sunday_closed',
            field=models.BooleanField(default=True, help_text='Marcar si el negocio cierra los domingos', verbose_name='Domingo Cerrado'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='schedule_sunday_start',
            field=models.CharField(blank=True, default='', help_text='Formato: 10:00 AM (dejar vacío si está cerrado)', max_length=10, verbose_name='Hora de Inicio (Domingo)'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='schedule_sunday_end',
            field=models.CharField(blank=True, default='', help_text='Formato: 2:00 PM (dejar vacío si está cerrado)', max_length=10, verbose_name='Hora de Fin (Domingo)'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='has_lunch_break',
            field=models.BooleanField(default=False, help_text='Marcar si el negocio cierra para almorzar', verbose_name='Cierra para Almorzar'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='lunch_break_start',
            field=models.CharField(blank=True, default='12:00 PM', help_text='Formato: 12:00 PM', max_length=10, verbose_name='Inicio del Almuerzo'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='lunch_break_end',
            field=models.CharField(blank=True, default='1:00 PM', help_text='Formato: 1:00 PM', max_length=10, verbose_name='Fin del Almuerzo'),
        ),
    ]
