# Generated by Django 5.2.8 on 2025-12-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_add_marketing_and_unlimited_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Ej: appointments, patients, sales', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('core', 'Núcleo'), ('medical', 'Médico'), ('sales', 'Ventas'), ('inventory', 'Inventario'), ('reports', 'Reportes'), ('settings', 'Configuración')], default='core', max_length=20)),
                ('icon', models.CharField(default='fa-cube', max_length=50, verbose_name='Ícono FontAwesome')),
                ('url_pattern', models.CharField(blank=True, help_text='Ej: /dashboard/appointments/', max_length=200, verbose_name='Patrón URL')),
                ('requires_view', models.BooleanField(default=True, verbose_name='Requiere permiso de Ver')),
                ('requires_create', models.BooleanField(default=True, verbose_name='Requiere permiso de Crear')),
                ('requires_edit', models.BooleanField(default=True, verbose_name='Requiere permiso de Editar')),
                ('requires_delete', models.BooleanField(default=True, verbose_name='Requiere permiso de Eliminar')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('doctor', 'Doctor/Optómetra'), ('staff', 'Personal'), ('cashier', 'Cajero'), ('viewer', 'Visualizador')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Puede Ver')),
                ('can_create', models.BooleanField(default=False, verbose_name='Puede Crear')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Puede Editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Puede Eliminar')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='organizations.organizationmember')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_permissions', to='organizations.modulepermission')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulos',
                'unique_together': {('member', 'module')},
            },
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='members', through='organizations.MemberModulePermission', to='organizations.modulepermission', verbose_name='Permisos Personalizados'),
        ),
    ]
