# Generated by Django 3.2.25 on 2026-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_modulepermission_organizationmember_invited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('doctor', 'Doctor/Optómetra'), ('staff', 'Personal'), ('cashier', 'Cajero'), ('vendedor', 'Vendedor'), ('viewer', 'Visualizador')], default='staff', max_length=20),
        ),
    ]
