# Generated by Django 3.2.25 on 2026-01-08 22:53

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0025_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('reminder', 'Recordatorio')], default='info', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('action_url', models.CharField(blank=True, help_text='URL a la que redirige al hacer clic', max_length=500, verbose_name='URL de Acción')),
                ('action_label', models.CharField(blank=True, help_text='Texto del botón de acción', max_length=100, verbose_name='Etiqueta del Botón')),
                ('metadata', apps.notifications.models.JSONFieldCompatible(blank=True, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_set', to='organizations.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único para la plantilla', max_length=100, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('title_template', models.CharField(max_length=200, verbose_name='Plantilla del Título')),
                ('message_template', models.TextField(verbose_name='Plantilla del Mensaje')),
                ('default_type', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('reminder', 'Recordatorio')], default='info', max_length=20, verbose_name='Tipo por Defecto')),
                ('default_channels', apps.notifications.models.JSONFieldCompatible(blank=True, help_text='Lista de canales a usar por defecto', verbose_name='Canales por Defecto')),
                ('expected_variables', apps.notifications.models.JSONFieldCompatible(blank=True, help_text='Lista de variables que acepta la plantilla', verbose_name='Variables Esperadas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationtemplate_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text='Código del tipo de notificación', max_length=100, verbose_name='Tipo de Notificación')),
                ('enabled_channels', apps.notifications.models.JSONFieldCompatible(blank=True, help_text='Lista de canales habilitados para este tipo', verbose_name='Canales Habilitados')),
                ('channel_config', apps.notifications.models.JSONFieldCompatible(blank=True, help_text='Configuración específica por canal', verbose_name='Configuración de Canales')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationpreference_set', to='organizations.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('system', 'Sistema (Dashboard)'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('delivered', 'Entregado'), ('read', 'Leído')], default='pending', max_length=20, verbose_name='Estado')),
                ('recipient', models.CharField(help_text='Email, número de teléfono, etc.', max_length=255, verbose_name='Destinatario')),
                ('response_data', apps.notifications.models.JSONFieldCompatible(blank=True, verbose_name='Respuesta del Servicio')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído el')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Intentos de Reenvío')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Máximo de Reintentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='notifications.notification', verbose_name='Notificación')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationchannel_set', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Canal de Notificación',
                'verbose_name_plural': 'Canales de Notificación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Lote')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('sending', 'Enviando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20, verbose_name='Estado')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total de Destinatarios')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Enviados')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Fallidos')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programado para')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationbatch_set', to='organizations.organization', verbose_name='Organización')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Lote de Notificaciones',
                'verbose_name_plural': 'Lotes de Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['code'], name='notificatio_code_ffac41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'organization'], name='notificatio_user_id_ca9dca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'organization', 'notification_type')},
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_22fd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_86e592_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'organization'], name='notificatio_user_id_79df2a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
